# Copyright (c) AIRBUS and its affiliates.
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

"""Generate the phase-graph A-Box from the live, admitted ``AUTOFDE_PHASE_GRAPH``.

``ontology/autofde-phase-graph.ttl`` is hand-authored (its own header says so) --
both the T-Box (vocabulary: ``afde:Phase``, ``afde:WorkItem``, ``afde:precedes``,
...) and a hand-transcribed copy of the A-Box (the individuals for this
repository's actual phases/work items). That A-Box copy is a parallel,
hand-maintained twin of ``AUTOFDE_PHASE_GRAPH`` with no generator and no
drift check -- unlike ``autofde-lab-capabilities.ttl``, which is generated
and CI-drift-tested (``fabric/ontology.py``).

This module closes that gap for the A-Box half only. It does **not** touch
the hand-authored T-Box: ``ontology/autofde-phase-graph.ttl`` stays exactly
as it is, vocabulary and all. This module emits a second file,
``ontology/autofde-phase-graph-instances.ttl``, containing only the
individuals -- generated directly from ``AUTOFDE_PHASE_GRAPH``, in the same
``afde:`` namespace, using exactly the predicates the hand-authored T-Box
already declares (``afde:nodeId``, ``afde:title``, ``afde:dueDate``,
``afde:phasePrecedes``, ``afde:inPhase``, ``afde:hasClassification``,
``afde:hasStatus``, ``afde:supersedes``, ``afde:occurrence``,
``afde:precedes``). A conformant RDF reader loads both files together to get
the complete graph (T-Box + generated A-Box) -- this file declares no
classes or properties of its own.

Like ``fabric/ontology.py``, this module computes structure only: nothing
here actuates, admits, brokers, or issues receipts.
"""

from __future__ import annotations

import sys
from pathlib import Path

from autofde_lab.autofde.phase_graph import AUTOFDE_PHASE_GRAPH, PhaseGraph

__all__ = ["emit_turtle", "generate"]

_HEADER = """\
# Copyright (c) AIRBUS and its affiliates.
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
#
# GENERATED by `python -m autofde_lab.autofde.ontology` -- do not hand-edit.
#
# The A-Box only, for the T-Box declared in the hand-authored
# ontology/autofde-phase-graph.ttl (same afde: namespace; load both files
# together for the complete graph). Generated directly from the live
# AUTOFDE_PHASE_GRAPH in src/autofde_lab/autofde/phase_graph.py -- if this
# file and that module ever disagree, this file is stale; regenerate it,
# never hand-edit it to match.

@prefix afde: <https://scikit-decide.local/autofde#> .
@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .
"""

#: WorkItem.kind values (Phase/WorkItem's own capitalization) map directly
#: onto the T-Box's afde:Classification individuals -- one-to-one, no
#: translation needed (both sides already agree on "Semantic"/"Infrastructure"/
#: "Runtime"/"Cloud"/"Verification").
_KNOWN_CLASSIFICATIONS = frozenset(
    {"Semantic", "Infrastructure", "Runtime", "Cloud", "Verification"}
)
_KNOWN_STATUSES = frozenset({"active", "superseded"})


def _turtle_string(value: str) -> str:
    """Escape a Python string for a single-line Turtle string literal."""
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def emit_turtle(graph: PhaseGraph = AUTOFDE_PHASE_GRAPH) -> str:
    """Render ``graph``'s A-Box as Turtle, in the hand-authored T-Box's vocabulary."""
    lines: list[str] = [_HEADER]

    lines.append("\n########################################################################")
    lines.append("# A-Box -- phases")
    lines.append("########################################################################\n")
    for phase in graph.phases:
        lines.append(f"afde:{phase.phase_id} a afde:Phase ;")
        lines.append(f'    afde:nodeId "{_turtle_string(phase.phase_id)}" ;')
        lines.append(f'    afde:title "{_turtle_string(phase.title)}" ;')
        lines.append(f'    afde:dueDate "{_turtle_string(phase.due_date)}" .')
    lines.append("")
    for phase in graph.phases:
        for pred_id in phase.after:
            lines.append(f"afde:{pred_id} afde:phasePrecedes afde:{phase.phase_id} .")
    lines.append("")

    lines.append("########################################################################")
    lines.append("# A-Box -- work items")
    lines.append("########################################################################\n")
    for item in graph.items:
        if item.kind not in _KNOWN_CLASSIFICATIONS:
            raise ValueError(
                f"work item {item.node_id!r} has kind {item.kind!r}, not one of "
                f"the T-Box's known afde:Classification individuals "
                f"{sorted(_KNOWN_CLASSIFICATIONS)} -- add the classification to "
                "ontology/autofde-phase-graph.ttl's T-Box before regenerating"
            )
        if item.status not in _KNOWN_STATUSES:
            raise ValueError(
                f"work item {item.node_id!r} has status {item.status!r}, not one "
                f"of the T-Box's known afde:Status individuals "
                f"{sorted(_KNOWN_STATUSES)}"
            )
        status_individual = "Active" if item.status == "active" else "Superseded"

        lines.append(f"afde:{item.node_id} a afde:WorkItem ;")
        lines.append(f'    afde:nodeId "{_turtle_string(item.node_id)}" ;')
        lines.append(f'    afde:title "{_turtle_string(item.title)}" ;')
        lines.append(f"    afde:inPhase afde:{item.phase} ;")
        lines.append(f"    afde:hasClassification afde:{item.kind} ;")
        lines.append(f"    afde:hasStatus afde:{status_individual} ;")
        if item.supersedes:
            lines.append(f"    afde:supersedes afde:{item.supersedes} ;")
        lines.append(f"    afde:occurrence {item.occurrence} .")
    lines.append("")

    lines.append("# --- work precedence ---------------------------------------------------\n")
    for item in graph.items:
        for req in item.requires:
            lines.append(f"afde:{req} afde:precedes afde:{item.node_id} .")
    lines.append("")

    return "\n".join(lines)


def generate(output_path: str, graph: PhaseGraph = AUTOFDE_PHASE_GRAPH) -> None:
    """Write ``emit_turtle(graph)`` to ``output_path``."""
    Path(output_path).write_text(emit_turtle(graph))


if __name__ == "__main__":
    target = sys.argv[1] if len(sys.argv) > 1 else "ontology/autofde-phase-graph-instances.ttl"
    generate(target)
    print(f"wrote {target}")
