// Copyright (c) AIRBUS and its affiliates.
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.
//
// Declarative GitHub project management for the AutoFDE phase graph.
//
// Structure follows the module in Engineering Elixir Applications ch. 2
// (see ~/dev/ranchr/bend/modules/integrations/github/project_management):
// content lives entirely in .auto.tfvars, which here is GENERATED by
// `python -m autofde_lab.autofde` from src/autofde_lab/autofde/phase_graph.py.
//
// READ THIS BEFORE ADDING AN EDGE.
// The resource graph below is a PROVISIONING graph: an edge means "needs this
// object's id to exist" (github_issue needs the milestone's .number). It is
// NOT a work-execution graph. Two issues where A blocks B and two fully
// independent issues in the same milestone with the same labels emit the
// identical resource graph here — so this graph is invariant under work order
// and carries zero bits about it. GitHub has no native blocks/blocked-by
// edge, so work precedence is carried in generated issue BODY metadata and is
// read back by autofde_lab.autofde.reconstruct. Never encode work order here.
//
// Apply authorized: explicit user go-ahead, 2026-08-07, per
// ~/.claude/plans/read-docs-autofde-explore-md-89-lines-ancient-hippo.md.
// github_repository.autofde targets the already-existing, already-renamed
// autofde-lab repo and must be `terraform import`ed before apply, never
// created fresh.

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 5.41"
    }
  }
}

locals {
  repository_name = "autofde-lab"
  github_owner    = "seanchatmangpt"
}

provider "github" {
  owner = local.github_owner
}

resource "github_repository" "autofde" {
  name                   = local.repository_name
  description            = "AI framework for Reinforcement Learning, Automated Planning and Scheduling."
  visibility             = "public"
  has_issues             = true
  auto_init              = true
  delete_branch_on_merge = true
}

variable "milestones" {
  type = map(object({
    title       = string
    due_date    = string
    description = string
  }))
  description = "Major phases. One milestone per admitted phase."
}

resource "github_repository_milestone" "epics" {
  for_each    = var.milestones
  owner       = local.github_owner
  repository  = local.repository_name
  title       = each.value.title
  description = replace(each.value.description, "\n", " ")
  due_date    = each.value.due_date
  depends_on  = [github_repository.autofde]
}

variable "labels" {
  type = map(object({
    name  = string
    color = string
  }))
  description = "Classification (Kind:*) and lineage (Status:*) labels."
}

resource "github_issue_label" "issues_labels" {
  for_each   = var.labels
  repository = local.repository_name
  name       = each.value.name
  color      = each.value.color
  depends_on = [github_repository.autofde]
}

variable "issues" {
  type = list(object({
    title     = string
    body      = string
    labels    = list(string)
    milestone = string
  }))
  description = <<EOT
Work items. `body` carries the autofde metadata block, which is the sole
carrier of work precedence in this projection.
EOT
}

resource "github_issue" "tasks" {
  count      = length(var.issues)
  repository = github_repository.autofde.name
  title      = var.issues[count.index].title
  body       = var.issues[count.index].body
  milestone_number = github_repository_milestone.epics[
    var.issues[count.index].milestone
  ].number
  labels = [for l in var.issues[count.index].labels :
    github_issue_label.issues_labels[l].name
  ]
}
