# GENERATED by `python -m autofde_lab.autofde` from the admitted AutoFDE
# phase graph (src/autofde_lab/autofde/phase_graph.py). Do not hand-edit.
#
# Work precedence is carried in issue-body metadata, never as a
# Terraform edge: the provisioning graph is invariant under work order.

milestones = {
  "semantic-foundation" = {
    title       = "Semantic Foundation"
    due_date    = "2026-08-14"
    description = <<EOT
The ontology, refusal vocabulary and standing-law terms every later phase is written against.
EOT
  },
  "project-infrastructure" = {
    title       = "Project Infrastructure"
    due_date    = "2026-08-21"
    description = <<EOT
Declarative project management and the CI gates that enforce the semantic foundation.
EOT
  },
  "azure-pack" = {
    title       = "Azure Pack"
    due_date    = "2026-09-04"
    description = <<EOT
Cloud landing zone and identity surfaces. Concurrent with Runtime Kernel: neither phase precedes the other.
EOT
  },
  "runtime-kernel" = {
    title       = "Runtime Kernel"
    due_date    = "2026-09-04"
    description = <<EOT
Bounded plan-structure execution machinery. Concurrent with Azure Pack: neither phase precedes the other.
EOT
  },
  "breach-clock-crown" = {
    title       = "Breach Clock Crown"
    due_date    = "2026-09-18"
    description = <<EOT
Deadline accounting and attestation over the joined kernel and cloud surfaces.
EOT
  },
}

labels = {
  "kind-cloud" = {
    name  = "Kind:Cloud"
    color = "1D76DB"
  },
  "kind-infrastructure" = {
    name  = "Kind:Infrastructure"
    color = "B60205"
  },
  "kind-runtime" = {
    name  = "Kind:Runtime"
    color = "0E8A16"
  },
  "kind-semantic" = {
    name  = "Kind:Semantic"
    color = "5319A1"
  },
  "kind-verification" = {
    name  = "Kind:Verification"
    color = "FBCA04"
  },
  "status-superseded" = {
    name  = "Status:Superseded"
    color = "666666"
  },
}

issues = [
  {
    title     = "Workload identity federation"
    body      = <<EOT
Federated credentials with no long-lived secret material.

<!-- autofde:begin -->
autofde-node: ap-identity
autofde-phase: azure-pack
autofde-kind: Cloud
autofde-occurrence: 1
autofde-status: active
autofde-requires: ap-landing-zone
autofde-supersedes: none
<!-- autofde:end -->
EOT
    labels    = ["kind-cloud"]
    milestone = "azure-pack"
  },
  {
    title     = "Azure landing zone"
    body      = <<EOT
Subscription, resource group and network scaffolding.

<!-- autofde:begin -->
autofde-node: ap-landing-zone
autofde-phase: azure-pack
autofde-kind: Cloud
autofde-occurrence: 1
autofde-status: active
autofde-requires: pi-terraform-module
autofde-supersedes: none
<!-- autofde:end -->
EOT
    labels    = ["kind-cloud"]
    milestone = "azure-pack"
  },
  {
    title     = "Breach attestation record"
    body      = <<EOT
A checkable record of what the clock observed. Records, never actuates.

<!-- autofde:begin -->
autofde-node: bc-attestation
autofde-phase: breach-clock-crown
autofde-kind: Verification
autofde-occurrence: 1
autofde-status: active
autofde-requires: bc-clock
autofde-supersedes: none
<!-- autofde:end -->
EOT
    labels    = ["kind-verification"]
    milestone = "breach-clock-crown"
  },
  {
    title     = "Breach clock"
    body      = <<EOT
Deadline accounting over the joined kernel and cloud surfaces.

<!-- autofde:begin -->
autofde-node: bc-clock
autofde-phase: breach-clock-crown
autofde-kind: Verification
autofde-occurrence: 1
autofde-status: active
autofde-requires: ap-identity, rk-bounds
autofde-supersedes: none
<!-- autofde:end -->
EOT
    labels    = ["kind-verification"]
    milestone = "breach-clock-crown"
  },
  {
    title     = "CI gate on the round-trip law"
    body      = <<EOT
Replans pi-ci-gate-v0 with a fresh occurrence identity. The gate reads precedence from generated issue-body metadata, never from the Terraform resource graph.

<!-- autofde:begin -->
autofde-node: pi-ci-gate
autofde-phase: project-infrastructure
autofde-kind: Infrastructure
autofde-occurrence: 2
autofde-status: active
autofde-requires: sf-refusal-vocab
autofde-supersedes: pi-ci-gate-v0
<!-- autofde:end -->
EOT
    labels    = ["kind-infrastructure"]
    milestone = "project-infrastructure"
  },
  {
    title     = "First CI gate attempt (superseded)"
    body      = <<EOT
Superseded: this attempt inferred work precedence from the Terraform resource graph, which is invariant under work order and therefore carries no bits about it.

<!-- autofde:begin -->
autofde-node: pi-ci-gate-v0
autofde-phase: project-infrastructure
autofde-kind: Infrastructure
autofde-occurrence: 1
autofde-status: superseded
autofde-requires: sf-refusal-vocab
autofde-supersedes: none
<!-- autofde:end -->
EOT
    labels    = ["kind-infrastructure", "status-superseded"]
    milestone = "project-infrastructure"
  },
  {
    title     = "Declarative GitHub project management module"
    body      = <<EOT
Milestones, labels and issues rendered from one admitted graph into a drop-in .auto.tfvars.

<!-- autofde:begin -->
autofde-node: pi-terraform-module
autofde-phase: project-infrastructure
autofde-kind: Infrastructure
autofde-occurrence: 1
autofde-status: active
autofde-requires: sf-ontology
autofde-supersedes: none
<!-- autofde:end -->
EOT
    labels    = ["kind-infrastructure"]
    milestone = "project-infrastructure"
  },
  {
    title     = "Execution bound accounting"
    body      = <<EOT
Account for every step against the declared bound; refuse on exhaustion.

<!-- autofde:begin -->
autofde-node: rk-bounds
autofde-phase: runtime-kernel
autofde-kind: Runtime
autofde-occurrence: 1
autofde-status: active
autofde-requires: rk-scheduler
autofde-supersedes: none
<!-- autofde:end -->
EOT
    labels    = ["kind-runtime"]
    milestone = "runtime-kernel"
  },
  {
    title     = "Bounded plan-structure scheduler"
    body      = <<EOT
Walk a partial order under an explicit execution bound.

<!-- autofde:begin -->
autofde-node: rk-scheduler
autofde-phase: runtime-kernel
autofde-kind: Runtime
autofde-occurrence: 1
autofde-status: active
autofde-requires: pi-terraform-module
autofde-supersedes: none
<!-- autofde:end -->
EOT
    labels    = ["kind-runtime"]
    milestone = "runtime-kernel"
  },
  {
    title     = "Author the AutoFDE phase-graph ontology"
    body      = <<EOT
Hand-author a T-Box and A-Box describing phases, work items and work precedence, so a projection can be checked against a declared vocabulary rather than against itself.

<!-- autofde:begin -->
autofde-node: sf-ontology
autofde-phase: semantic-foundation
autofde-kind: Semantic
autofde-occurrence: 1
autofde-status: active
autofde-requires: none
autofde-supersedes: none
<!-- autofde:end -->
EOT
    labels    = ["kind-semantic"]
    milestone = "semantic-foundation"
  },
  {
    title     = "Name every AutoFDE refusal"
    body      = <<EOT
Every rejection names a specific law. No bare strings, no generic ValueError text.

<!-- autofde:begin -->
autofde-node: sf-refusal-vocab
autofde-phase: semantic-foundation
autofde-kind: Semantic
autofde-occurrence: 1
autofde-status: active
autofde-requires: none
autofde-supersedes: none
<!-- autofde:end -->
EOT
    labels    = ["kind-semantic"]
    milestone = "semantic-foundation"
  },
]
