"""Domain-evidence registry -- real per-domain facts needed to drive the
generic OCEL episode runner (`scripts/run_domain_gymact_ocel_episode.py`) and
generic standalone verifier (`scripts/verify_domain_episode.py`).

Manufactured by `ggen sync run` from `ontology/domain-evidence.ttl` via
`queries/domain-evidence/registry.rq`: one `DomainEvidenceSpec` per real
`afl:DomainEvidenceSpec` individual, per
`docs/jira/2026-08-13-domain-maturity-l4/INDEX-AND-GGEN-DESIGN.md`'s
"autofde-domain-evidence-pack" design. Adding a new domain to the L4-push
pipeline means adding one new ontology individual, not writing a new script
or verifier -- the generic runner/verifier below consume this registry.

`solver_candidates` is the planner-of-planners extension: an ordered list of
named solver strategies the runner's dispatcher tries in turn, each with a
real bounded timeout, falling through to the next on a real timeout/error
(receipted as `ev:solver_refused` OCEL events) -- not a human hardcoding one
`if domain_key == ...` branch per domain.

`verify_candidates` is the SAME pattern applied to verify_mode: an ordered
list of named verify strategies the runner's `_run_verify_portfolio`
dispatcher tries in turn, each with a real bounded timeout, falling through
to the next on a real timeout/failed check (receipted as
`ev:verifier_refused` / `ev:verifier_selected` OCEL events). Domains with no
`verify_candidates` fall back to the legacy single `verify_mode` string.

GENERATED by ggen. DO NOT EDIT BY HAND -- edit
`ontology/domain-evidence.ttl` and re-run `ggen sync run` from the repo root
to regenerate.
"""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class CapabilitySpec:
    """One DO/OBSERVE capability of a domain, with its precondition
    expression (a Python boolean expression evaluated with `state` and
    `action` bound)."""

    name: str
    consequence: str
    precondition_expr: str


@dataclass(frozen=True)
class SolverCandidateSpec:
    """One ordered solver-strategy attempt for a domain, with a real
    bounded timeout. `strategy` is a closed name the runner's
    `_SOLVER_STRATEGIES` dict knows how to build+solve+rollout."""

    order: int
    strategy: str
    timeout_seconds: int


@dataclass(frozen=True)
class VerifyCandidateSpec:
    """One ordered verify-strategy attempt for a domain, with a real
    bounded timeout. `strategy` is a closed name the runner's
    `_VERIFY_STRATEGIES` dict knows how to independently check."""

    order: int
    strategy: str
    timeout_seconds: int


@dataclass(frozen=True)
class DomainEvidenceSpec:
    """Real facts about one hub domain needed to generate/drive its OCEL
    episode + standalone verifier."""

    domain_name: str
    python_module_path: str
    domain_class_name: str
    bridge_module_path: str
    bridge_class_name: str
    goal_check_expr: str
    verify_mode: str
    evidence_out_path: str
    capabilities: tuple[CapabilitySpec, ...] = field(default_factory=tuple)
    solver_candidates: tuple[SolverCandidateSpec, ...] = field(default_factory=tuple)
    verify_candidates: tuple[VerifyCandidateSpec, ...] = field(default_factory=tuple)


DOMAIN_EVIDENCE_REGISTRY: dict[str, DomainEvidenceSpec] = {

"breach_clock": DomainEvidenceSpec(
        domain_name="breach_clock",
        python_module_path="autofde_lab.hub.domain.breach_clock.breach_clock",
        domain_class_name="BreachClockDomain",
        bridge_module_path="",
        bridge_class_name="",
        goal_check_expr="state.notification is Notification.DELIVERED and state.notified_populations == state.populations",
        verify_mode="fresh-instance-replay",
        evidence_out_path="docs/evidence/breach_clock/domain-evidence-episode.ocel.json",
        capabilities=(
            CapabilitySpec(name="deliver_notification", consequence="DO", precondition_expr="state.notification is Notification.DRAFTED and state.notified_populations == state.populations"),
        ),
        solver_candidates=(
            SolverCandidateSpec(order=1, strategy="astar-plain", timeout_seconds=20),
            SolverCandidateSpec(order=2, strategy="lrtastar-plain", timeout_seconds=20),
        ),
        verify_candidates=(
            VerifyCandidateSpec(order=1, strategy="fresh-instance-replay", timeout_seconds=15),
            VerifyCandidateSpec(order=2, strategy="independent-resolve", timeout_seconds=30),
        ),
    ),

"career_admission": DomainEvidenceSpec(
        domain_name="career_admission",
        python_module_path="autofde_lab.hub.domain.career_admission.career_admission",
        domain_class_name="CareerAdmission",
        bridge_module_path="",
        bridge_class_name="",
        goal_check_expr="self._required_categories.issubset({self._facts[fact_id].category for fact_id in state.admitted if fact_id in self._facts})",
        verify_mode="fresh-instance-replay",
        evidence_out_path="docs/evidence/career_admission/domain-evidence-episode.ocel.json",
        capabilities=(
            CapabilitySpec(name="intuit_automl", consequence="DO", precondition_expr="fact.id not in admitted and set(fact.prerequisite_ids).issubset(admitted)"),
        ),
        solver_candidates=(
            SolverCandidateSpec(order=1, strategy="astar-plain", timeout_seconds=15),
            SolverCandidateSpec(order=2, strategy="lrtastar-plain", timeout_seconds=15),
        ),
        verify_candidates=(
            VerifyCandidateSpec(order=1, strategy="fresh-instance-replay", timeout_seconds=15),
            VerifyCandidateSpec(order=2, strategy="independent-resolve", timeout_seconds=30),
        ),
    ),

"chatman_clean_session": DomainEvidenceSpec(
        domain_name="chatman_clean_session",
        python_module_path="autofde_lab.hub.domain.chatman_clean_session",
        domain_class_name="ChatmanCleanSessionDomain",
        bridge_module_path="",
        bridge_class_name="",
        goal_check_expr="state.stage == Stage.STANDING and state.standing == 'ALIVE'",
        verify_mode="fresh-instance-replay",
        evidence_out_path="docs/evidence/chatman_clean_session/domain-evidence-episode.ocel.json",
        capabilities=(
            CapabilitySpec(name="try_route", consequence="DO", precondition_expr="state.stage == Stage.ROUTE"),
        ),
        solver_candidates=(
            SolverCandidateSpec(order=1, strategy="astar-plain", timeout_seconds=20),
            SolverCandidateSpec(order=2, strategy="lrtastar-plain", timeout_seconds=20),
        ),
        verify_candidates=(
        ),
    ),

"cloudgoat_iam_privesc": DomainEvidenceSpec(
        domain_name="cloudgoat_iam_privesc",
        python_module_path="autofde_lab.hub.domain.cloudgoat_iam_privesc.cloudgoat_iam_privesc",
        domain_class_name="CloudGoatIamPrivescDomain",
        bridge_module_path="",
        bridge_class_name="",
        goal_check_expr="state.enumerated and state.admin_role_on_profile and state.keypair_created and state.instance_launched and state.has_shell_access and state.target_terminated",
        verify_mode="fresh-instance-replay",
        evidence_out_path="docs/evidence/cloudgoat_iam_privesc/domain-evidence-episode.ocel.json",
        capabilities=(
            CapabilitySpec(name="terminate_target_instance", consequence="DO", precondition_expr="state.has_shell_access and not state.target_terminated"),
        ),
        solver_candidates=(
            SolverCandidateSpec(order=1, strategy="astar-plain", timeout_seconds=20),
            SolverCandidateSpec(order=2, strategy="lrtastar-plain", timeout_seconds=20),
        ),
        verify_candidates=(
            VerifyCandidateSpec(order=1, strategy="fresh-instance-replay", timeout_seconds=15),
            VerifyCandidateSpec(order=2, strategy="independent-resolve", timeout_seconds=30),
        ),
    ),

"fix_git": DomainEvidenceSpec(
        domain_name="fix_git",
        python_module_path="autofde_lab.hub.domain.fix_git",
        domain_class_name="GitRecoveryDomain",
        bridge_module_path="",
        bridge_class_name="",
        goal_check_expr="memory.current_branch == self.base_branch and memory.recovery_branch_exists and memory.merged",
        verify_mode="fresh-instance-replay",
        evidence_out_path="docs/evidence/fix_git/domain-evidence-episode.ocel.json",
        capabilities=(
            CapabilitySpec(name="merge_recovery", consequence="DO", precondition_expr="memory.current_branch == self.base_branch and memory.recovery_branch_exists and not memory.merged"),
            CapabilitySpec(name="merge_recovery", consequence="DO", precondition_expr="memory.current_branch == self.base_branch and memory.recovery_branch_exists and not memory.merged"),
            CapabilitySpec(name="merge_recovery", consequence="DO", precondition_expr="memory.current_branch == self.base_branch and memory.recovery_branch_exists and not memory.merged"),
            CapabilitySpec(name="merge_recovery", consequence="DO", precondition_expr="memory.current_branch == self.base_branch and memory.recovery_branch_exists and not memory.merged"),
        ),
        solver_candidates=(
            SolverCandidateSpec(order=1, strategy="astar-plain", timeout_seconds=20),
            SolverCandidateSpec(order=2, strategy="lrtastar-plain", timeout_seconds=20),
        ),
        verify_candidates=(
        ),
    ),

"flight_planning": DomainEvidenceSpec(
        domain_name="flight_planning",
        python_module_path="autofde_lab.hub.domain.flight_planning.domain",
        domain_class_name="FlightPlanningDomain",
        bridge_module_path="",
        bridge_class_name="",
        goal_check_expr="destination reached within tolerance, per _get_goals_",
        verify_mode="fresh-instance-replay",
        evidence_out_path="docs/evidence/flight_planning/domain-evidence-episode.ocel.json",
        capabilities=(
            CapabilitySpec(name="H_Action,V_Action tuple  # horizontal/vertical routing action", consequence="DO", precondition_expr="per _get_applicable_actions_from"),
        ),
        solver_candidates=(
            SolverCandidateSpec(order=1, strategy="astar-plain", timeout_seconds=20),
            SolverCandidateSpec(order=2, strategy="astar-heuristic", timeout_seconds=30),
        ),
        verify_candidates=(
        ),
    ),

"graph_domain": DomainEvidenceSpec(
        domain_name="graph_domain",
        python_module_path="autofde_lab.hub.domain.graph_domain.GraphDomain",
        domain_class_name="GraphDomain",
        bridge_module_path="",
        bridge_class_name="",
        goal_check_expr="state in self.targets  # inherited from FullSpaceExploration(source_domain)'s admitted goal set",
        verify_mode="fresh-instance-replay",
        evidence_out_path="docs/evidence/graph_domain/domain-evidence-episode.ocel.json",
        capabilities=(
            CapabilitySpec(name="right  # single edge label of the pilot ChainDomain source", consequence="DO", precondition_expr="edge exists in the explored graph"),
        ),
        solver_candidates=(
            SolverCandidateSpec(order=1, strategy="astar-plain", timeout_seconds=15),
            SolverCandidateSpec(order=2, strategy="iw-state-features", timeout_seconds=15),
        ),
        verify_candidates=(
        ),
    ),

"gym": DomainEvidenceSpec(
        domain_name="gym",
        python_module_path="autofde_lab.hub.domain.gym",
        domain_class_name="GymDomain",
        bridge_module_path="",
        bridge_class_name="",
        goal_check_expr="N/A -- MountainCarContinuous-v0 is a continuous-control env with no discrete goal reachable by Astar; closed via seeded-trajectory-replay",
        verify_mode="seeded-trajectory-replay",
        evidence_out_path="docs/evidence/gym/domain-evidence-episode.ocel.json",
        capabilities=(
            CapabilitySpec(name="continuous_action (Box)", consequence="DO", precondition_expr="within action_space bounds"),
        ),
        solver_candidates=(
        ),
        verify_candidates=(
        ),
    ),

"k8s_goat_rbac_escalation": DomainEvidenceSpec(
        domain_name="k8s_goat_rbac_escalation",
        python_module_path="autofde_lab.hub.domain.k8s_goat_rbac_escalation.k8s_goat_rbac_escalation",
        domain_class_name="K8sGoatRBACEscalation",
        bridge_module_path="",
        bridge_class_name="",
        goal_check_expr="GOAL_STEP_ID in state.known",
        verify_mode="fresh-instance-replay",
        evidence_out_path="docs/evidence/k8s_goat_rbac_escalation/domain-evidence-episode.ocel.json",
        capabilities=(
            CapabilitySpec(name="read_and_decode_k8svaultapikey", consequence="DO", precondition_expr="'list_namespace_secrets' in known"),
        ),
        solver_candidates=(
            SolverCandidateSpec(order=1, strategy="astar-plain", timeout_seconds=20),
            SolverCandidateSpec(order=2, strategy="lrtastar-plain", timeout_seconds=20),
        ),
        verify_candidates=(
        ),
    ),

"mastermind": DomainEvidenceSpec(
        domain_name="mastermind",
        python_module_path="autofde_lab.hub.domain.mastermind.mastermind",
        domain_class_name="MasterMind",
        bridge_module_path="",
        bridge_class_name="",
        goal_check_expr="score == Score(total_bulls=n_positions, total_cows=0)",
        verify_mode="independent-resolve",
        evidence_out_path="docs/evidence/mastermind/domain-evidence-episode.ocel.json",
        capabilities=(
            CapabilitySpec(name="guess(row)", consequence="DO", precondition_expr="true (UnrestrictedActions -- any row in the enumerable action space is always applicable)"),
        ),
        solver_candidates=(
        ),
        verify_candidates=(
        ),
    ),

"maze": DomainEvidenceSpec(
        domain_name="maze",
        python_module_path="autofde_lab.hub.domain.maze.maze",
        domain_class_name="Maze",
        bridge_module_path="",
        bridge_class_name="",
        goal_check_expr="state == self._goal",
        verify_mode="fresh-instance-replay",
        evidence_out_path="docs/evidence/maze/domain-evidence-episode.ocel.json",
        capabilities=(
            CapabilitySpec(name="up|down|left|right", consequence="DO", precondition_expr="true"),
        ),
        solver_candidates=(
            SolverCandidateSpec(order=1, strategy="astar-plain", timeout_seconds=30),
            SolverCandidateSpec(order=2, strategy="lrtastar-plain", timeout_seconds=30),
        ),
        verify_candidates=(
            VerifyCandidateSpec(order=1, strategy="fresh-instance-replay", timeout_seconds=15),
            VerifyCandidateSpec(order=2, strategy="independent-resolve", timeout_seconds=30),
        ),
    ),

"pddl": DomainEvidenceSpec(
        domain_name="pddl",
        python_module_path="autofde_lab.hub.domain.pddl.domain",
        domain_class_name="PDDLDomain",
        bridge_module_path="",
        bridge_class_name="",
        goal_check_expr="self._goal_checker.is_goal(s.to_cpp())  # C++ CppGoalChecker compiled from the loaded PDDL domain/problem file; for the proven fixture (blocks-3-0) the goal is 'on(b, c)'",
        verify_mode="fresh-instance-replay",
        evidence_out_path="docs/evidence/pddl/domain-evidence-episode.ocel.json",
        capabilities=(
            CapabilitySpec(name="PDDLAction  # grounded action instance, e.g. (pick-up|stack|...) — dynamically enumerated per problem file, not a fixed constant", consequence="DO", precondition_expr="self._aops_gen.get_applicable_actions(memory.to_cpp())  # C++ delete-relaxation-free applicability generator over the PDDL task's compiled action schema; no static Python precondition expression exists in this module"),
            CapabilitySpec(name="PDDLAction  # grounded action, enumerated per problem file", consequence="DO", precondition_expr="self._aops_gen.get_applicable_actions(memory.to_cpp())"),
            CapabilitySpec(name="PDDLAction  # grounded action, enumerated per problem file", consequence="DO", precondition_expr="self._aops_gen.get_applicable_actions(memory.to_cpp())  # C++ delete-relaxation-free applicability generator over the PDDL task's compiled action schema; no static Python precondition expression exists in this module"),
            CapabilitySpec(name="PDDLAction  # grounded action instance, e.g. (pick-up|stack|...) — dynamically enumerated per problem file, not a fixed constant", consequence="DO", precondition_expr="self._aops_gen.get_applicable_actions(memory.to_cpp())"),
            CapabilitySpec(name="PDDLAction  # grounded action instance, e.g. (pick-up|stack|...) — dynamically enumerated per problem file, not a fixed constant", consequence="DO", precondition_expr="self._aops_gen.get_applicable_actions(memory.to_cpp())  # C++ delete-relaxation-free applicability generator over the PDDL task's compiled action schema; no static Python precondition expression exists in this module"),
            CapabilitySpec(name="PDDLAction  # grounded action, enumerated per problem file", consequence="DO", precondition_expr="self._aops_gen.get_applicable_actions(memory.to_cpp())"),
            CapabilitySpec(name="PDDLAction  # grounded action, enumerated per problem file", consequence="DO", precondition_expr="self._aops_gen.get_applicable_actions(memory.to_cpp())  # C++ delete-relaxation-free applicability generator over the PDDL task's compiled action schema; no static Python precondition expression exists in this module"),
            CapabilitySpec(name="PDDLAction  # grounded action instance, e.g. (pick-up|stack|...) — dynamically enumerated per problem file, not a fixed constant", consequence="DO", precondition_expr="self._aops_gen.get_applicable_actions(memory.to_cpp())"),
            CapabilitySpec(name="PDDLAction  # grounded action instance, e.g. (pick-up|stack|...) — dynamically enumerated per problem file, not a fixed constant", consequence="DO", precondition_expr="self._aops_gen.get_applicable_actions(memory.to_cpp())"),
            CapabilitySpec(name="PDDLAction  # grounded action instance, e.g. (pick-up|stack|...) — dynamically enumerated per problem file, not a fixed constant", consequence="DO", precondition_expr="self._aops_gen.get_applicable_actions(memory.to_cpp())  # C++ delete-relaxation-free applicability generator over the PDDL task's compiled action schema; no static Python precondition expression exists in this module"),
            CapabilitySpec(name="PDDLAction  # grounded action, enumerated per problem file", consequence="DO", precondition_expr="self._aops_gen.get_applicable_actions(memory.to_cpp())"),
            CapabilitySpec(name="PDDLAction  # grounded action, enumerated per problem file", consequence="DO", precondition_expr="self._aops_gen.get_applicable_actions(memory.to_cpp())  # C++ delete-relaxation-free applicability generator over the PDDL task's compiled action schema; no static Python precondition expression exists in this module"),
            CapabilitySpec(name="PDDLAction  # grounded action instance, e.g. (pick-up|stack|...) — dynamically enumerated per problem file, not a fixed constant", consequence="DO", precondition_expr="self._aops_gen.get_applicable_actions(memory.to_cpp())"),
            CapabilitySpec(name="PDDLAction  # grounded action instance, e.g. (pick-up|stack|...) — dynamically enumerated per problem file, not a fixed constant", consequence="DO", precondition_expr="self._aops_gen.get_applicable_actions(memory.to_cpp())  # C++ delete-relaxation-free applicability generator over the PDDL task's compiled action schema; no static Python precondition expression exists in this module"),
            CapabilitySpec(name="PDDLAction  # grounded action, enumerated per problem file", consequence="DO", precondition_expr="self._aops_gen.get_applicable_actions(memory.to_cpp())"),
            CapabilitySpec(name="PDDLAction  # grounded action, enumerated per problem file", consequence="DO", precondition_expr="self._aops_gen.get_applicable_actions(memory.to_cpp())  # C++ delete-relaxation-free applicability generator over the PDDL task's compiled action schema; no static Python precondition expression exists in this module"),
        ),
        solver_candidates=(
            SolverCandidateSpec(order=1, strategy="astar-plain", timeout_seconds=15),
            SolverCandidateSpec(order=2, strategy="lrtastar-plain", timeout_seconds=15),
        ),
        verify_candidates=(
        ),
    ),

"plado": DomainEvidenceSpec(
        domain_name="plado",
        python_module_path="autofde_lab.hub.domain.plado",
        domain_class_name="PladoPddlDomain",
        bridge_module_path="",
        bridge_class_name="",
        goal_check_expr="self.is_goal(state)  # blocks-3-0 fixture, native encoding, real Astar-solvable in 4 steps -- closes a real pre-existing test gap (test_plado_domain_planning never asserted goal-reaching)",
        verify_mode="fresh-instance-replay",
        evidence_out_path="docs/evidence/plado/domain-evidence-episode.ocel.json",
        capabilities=(
            CapabilitySpec(name="PladoAction  # native-encoded grounded action", consequence="DO", precondition_expr="applicable per native PDDL applicability generator"),
        ),
        solver_candidates=(
            SolverCandidateSpec(order=1, strategy="astar-plain", timeout_seconds=15),
            SolverCandidateSpec(order=2, strategy="lrtastar-plain", timeout_seconds=15),
        ),
        verify_candidates=(
        ),
    ),

"rcpsp": DomainEvidenceSpec(
        domain_name="rcpsp",
        python_module_path="autofde_lab.hub.domain.rcpsp.rcpsp_sk",
        domain_class_name="RCPSP",
        bridge_module_path="",
        bridge_class_name="",
        goal_check_expr="state.tasks_complete == state.task_ids  # all 32 j301_1.sm tasks complete",
        verify_mode="independent-resolve",
        evidence_out_path="docs/evidence/rcpsp/domain-evidence-episode.ocel.json",
        capabilities=(
            CapabilitySpec(name="start_task(task_id, mode)", consequence="DO", precondition_expr="precedence + resource constraints satisfied (SGS_PRECEDENCE policy)"),
        ),
        solver_candidates=(
            SolverCandidateSpec(order=1, strategy="astar-plain", timeout_seconds=20),
            SolverCandidateSpec(order=2, strategy="do-solver-cpsat", timeout_seconds=60),
        ),
        verify_candidates=(
        ),
    ),

"rddl": DomainEvidenceSpec(
        domain_name="rddl",
        python_module_path="autofde_lab.hub.domain.rddl.rddl",
        domain_class_name="RDDLDomain",
        bridge_module_path="",
        bridge_class_name="",
        goal_check_expr="N/A -- stochastic RLDomain (pyRDDLGym CartPole_Continuous_gym), no deterministic goal; closed via seeded-trajectory-replay (seeded RNG, bitwise-identical replay proven)",
        verify_mode="seeded-trajectory-replay",
        evidence_out_path="docs/evidence/rddl/domain-evidence-episode.ocel.json",
        capabilities=(
            CapabilitySpec(name="force (continuous, bounded [-10,10])", consequence="DO", precondition_expr="within real force bounds read from env.action_space"),
        ),
        solver_candidates=(
        ),
        verify_candidates=(
        ),
    ),

"rock_paper_scissors": DomainEvidenceSpec(
        domain_name="rock_paper_scissors",
        python_module_path="autofde_lab.hub.domain.rock_paper_scissors.rock_paper_scissors",
        domain_class_name="RockPaperScissors",
        bridge_module_path="",
        bridge_class_name="",
        goal_check_expr="N/A -- no single-agent goal; terminal condition is num_move >= max_moves, closed via seeded-trajectory-replay instead",
        verify_mode="seeded-trajectory-replay",
        evidence_out_path="docs/evidence/rock_paper_scissors/domain-evidence-episode.ocel.json",
        capabilities=(
            CapabilitySpec(name="submit_moves(player1, player2)", consequence="DO", precondition_expr="true"),
        ),
        solver_candidates=(
        ),
        verify_candidates=(
        ),
    ),

"simple_grid_world": DomainEvidenceSpec(
        domain_name="simple_grid_world",
        python_module_path="autofde_lab.hub.domain.simple_grid_world",
        domain_class_name="SimpleGridWorld",
        bridge_module_path="",
        bridge_class_name="",
        goal_check_expr="state == State(x=num_cols-1, y=num_rows-1)",
        verify_mode="fresh-instance-replay",
        evidence_out_path="docs/evidence/simple_grid_world/domain-evidence-episode.ocel.json",
        capabilities=(
            CapabilitySpec(name="up|down|left|right", consequence="DO", precondition_expr="true (UnrestrictedActions, wall-clamped at grid edges)"),
        ),
        solver_candidates=(
            SolverCandidateSpec(order=1, strategy="astar-plain", timeout_seconds=15),
            SolverCandidateSpec(order=2, strategy="bfws-state-features", timeout_seconds=15),
        ),
        verify_candidates=(
        ),
    ),

"tai_v30_1_1": DomainEvidenceSpec(
        domain_name="tai_v30_1_1",
        python_module_path="autofde_lab.hub.domain.tai_v30_1_1.tai_v30_1_1",
        domain_class_name="TAIForwardDeploymentDomain",
        bridge_module_path="",
        bridge_class_name="",
        goal_check_expr="state.standing == True",
        verify_mode="fresh-instance-replay",
        evidence_out_path="docs/evidence/tai_v30_1_1/domain-evidence-episode.ocel.json",
        capabilities=(
            CapabilitySpec(name="compile_enterprise", consequence="DO", precondition_expr="not state.enterprise_compiled"),
        ),
        solver_candidates=(
            SolverCandidateSpec(order=1, strategy="astar-plain", timeout_seconds=20),
            SolverCandidateSpec(order=2, strategy="lrtastar-plain", timeout_seconds=20),
        ),
        verify_candidates=(
        ),
    ),

"terragoat": DomainEvidenceSpec(
        domain_name="terragoat",
        python_module_path="autofde_lab.hub.domain.terragoat.terragoat_remediation",
        domain_class_name="TerraGoatRemediation",
        bridge_module_path="",
        bridge_class_name="",
        goal_check_expr="len(state.open_findings) == 0",
        verify_mode="fresh-instance-replay",
        evidence_out_path="docs/evidence/terragoat/domain-evidence-episode.ocel.json",
        capabilities=(
            CapabilitySpec(name="close_finding", consequence="DO", precondition_expr="finding_id in state.open_findings"),
        ),
        solver_candidates=(
            SolverCandidateSpec(order=1, strategy="astar-plain", timeout_seconds=20),
            SolverCandidateSpec(order=2, strategy="lrtastar-plain", timeout_seconds=20),
        ),
        verify_candidates=(
        ),
    ),

"up": DomainEvidenceSpec(
        domain_name="up",
        python_module_path="autofde_lab.hub.domain.up",
        domain_class_name="UPDomain",
        bridge_module_path="",
        bridge_class_name="",
        goal_check_expr="self._simulator.is_goal(state.up_state)",
        verify_mode="fresh-instance-replay",
        evidence_out_path="docs/evidence/up/domain-evidence-episode.ocel.json",
        capabilities=(
            CapabilitySpec(name="SkUPAction", consequence="DO", precondition_expr="true"),
            CapabilitySpec(name="SkUPAction", consequence="DO", precondition_expr="true"),
        ),
        solver_candidates=(
            SolverCandidateSpec(order=1, strategy="astar-plain", timeout_seconds=15),
            SolverCandidateSpec(order=2, strategy="lrtastar-plain", timeout_seconds=15),
        ),
        verify_candidates=(
        ),
    ),
}
