"""AutoFDE Lab semantic constitution — direct Python projection.

Manufactured by `ggen sync run` from an ontology/*.ttl file in the merged
working-backwards Lab constitution (PR #37). Manufacture is provenance, not
architecture (ontology/manufacture.ttl) -- this is ordinary source at its
ordinary import path, additive only, and is not wired into any existing
runtime code path (no planner, no level4_crown, no gymact bridge imports it).

Object-property fields hold an identity-reference string (the referenced
object's own identity), never a resolved object -- this is a thin semantic
projection, not an ORM. Non-functional properties render as a tuple of
reference strings; functional properties render as an optional single
reference string. The ontology asserts no required cardinality anywhere, so
every field defaults to empty/None rather than being required.

GENERATED by ggen. DO NOT EDIT BY HAND -- edit the source ontology/*.ttl file
and re-run `ggen sync run` from the repo root to regenerate.
"""
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum



class StandingValue(str, Enum):
    """Status-vocabulary named individuals from this ontology file."""

    BEHAVIORAL = "BEHAVIORAL"
    EVIDENCE = "EVIDENCE"
    STRUCTURAL = "STRUCTURAL"
    CERT_BUILD_BROKEN = "CERT_BUILD_BROKEN"
    CERT_UNSUPPORTED = "CERT_UNSUPPORTED"
    SMOKE_TESTED = "SMOKE_TESTED"
    STRUCTURAL_ONLY = "STRUCTURAL_ONLY"
    NO_ARGS = "NO_ARGS"
    SOLUTION_DURATION_NO_TRACE = "SOLUTION_DURATION_NO_TRACE"
    SOLUTION_ONLY = "SOLUTION_ONLY"
    SOLUTION_TRACE_DURATION_OPTIONAL = "SOLUTION_TRACE_DURATION_OPTIONAL"
    VARARGS = "VARARGS"



@dataclass(frozen=True)
class CertificationCheck:
    """A real, atomic, named conformance check definition -- e.g. 'environment_has_all_seven_methods', 'capability_consequence_is_valid'. Defining this closes the TYPE gap only; the real check logic lives in gymact_certification_checker.py, never generated."""
    check_description: str | None = None  #  (ref: http://www.w3.org/2001/XMLSchema#string)
    check_name: str | None = None  #  (ref: http://www.w3.org/2001/XMLSchema#string)
    check_severity_ref: str | None = None  #  (ref: CheckSeverity)


@dataclass(frozen=True)
class CertificationCheckResult:
    """The real, honest outcome of one real, executed CertificationCheck. resultPassed is a real, external, already-decided bool (matching guard_executor.ExecutionStep.failed's own precedent for when a bare bool is legitimate) -- never a value this repo computes twice. resultEvidenceRef is populated only when the check executed a real gymact operation whose receipt is independently verifiable; a pure structural check leaves it unset, never fabricated."""
    result_check_ref: str | None = None  #  (ref: http://www.w3.org/2001/XMLSchema#string)
    result_detail: str | None = None  #  (ref: http://www.w3.org/2001/XMLSchema#string)
    result_evidence_ref: str | None = None  #  (ref: http://www.w3.org/2001/XMLSchema#string)
    result_passed: str | None = None  #  (ref: http://www.w3.org/2001/XMLSchema#boolean)


@dataclass(frozen=True)
class CertificationManifest:
    """The real, top-level output of one gymact_certification_checker run against one real EnvironmentProvider/Environment instance. manifestConformanceLevel is computed honestly from real check results -- never asserted independent of them. This is never a badge issued in advance of real checks; constructing this type does not itself certify anything."""
    manifest_check_result_ref: tuple[str, ...] = ()  #  (ref: http://www.w3.org/2001/XMLSchema#string)
    manifest_computation_receipt_ref: str | None = None  #  (ref: http://www.w3.org/2001/XMLSchema#string)
    manifest_conformance_level_ref: str | None = None  #  (ref: ConformanceLevel)
    manifest_gym_name: str | None = None  #  (ref: http://www.w3.org/2001/XMLSchema#string)
    manifest_issued_at_ref: str | None = None  #  (ref: http://www.w3.org/2001/XMLSchema#string)
    manifest_provider_class_ref: str | None = None  #  (ref: http://www.w3.org/2001/XMLSchema#string)


@dataclass(frozen=True)
class OracleContractFinding:
    """One real, statically-derived (ast.parse over real vendored source text, never an import) classification of one real Oracle subclass's evaluate() method. This is exhaustive over every file scanned -- every oracle class found gets a real finding, never silently dropped. findingReturnTypeAnnotationMismatch is a real, syntactic heuristic (annotation says one type, a real return statement in the body returns a dict literal) -- named as a heuristic, never claimed as a full type-checker."""
    finding_evaluate_arg_shape_ref: str | None = None  #  (ref: EvaluateArgShape)
    finding_oracle_class_name: str | None = None  #  (ref: http://www.w3.org/2001/XMLSchema#string)
    finding_return_type_annotation_mismatch: str | None = None  #  (ref: http://www.w3.org/2001/XMLSchema#boolean)
    finding_source_file_ref: str | None = None  #  (ref: http://www.w3.org/2001/XMLSchema#string)


__all__ = [
    "StandingValue",
    "CertificationCheck",
    "CertificationCheckResult",
    "CertificationManifest",
    "OracleContractFinding",
]
