"""AutoFDE Lab semantic constitution — direct Python projection.

Manufactured by `ggen sync run` from an ontology/*.ttl file in the merged
working-backwards Lab constitution (PR #37). Manufacture is provenance, not
architecture (ontology/manufacture.ttl) -- this is ordinary source at its
ordinary import path, additive only, and is not wired into any existing
runtime code path (no planner, no level4_crown, no gymact bridge imports it).

Object-property fields hold an identity-reference string (the referenced
object's own identity), never a resolved object -- this is a thin semantic
projection, not an ORM. Non-functional properties render as a tuple of
reference strings; functional properties render as an optional single
reference string. The ontology asserts no required cardinality anywhere, so
every field defaults to empty/None rather than being required.

GENERATED by ggen. DO NOT EDIT BY HAND -- edit the source ontology/*.ttl file
and re-run `ggen sync run` from the repo root to regenerate.
"""
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum



class StandingValue(str, Enum):
    """Status-vocabulary named individuals from this ontology file."""

    Approved = "Approved"
    PendingHumanApproval = "PendingHumanApproval"
    Rejected = "Rejected"
    ArchitectureBoard = "ArchitectureBoard"
    ArchitectureOwner = "ArchitectureOwner"
    ImplementationGovernanceBoard = "ImplementationGovernanceBoard"
    IntegratedInfoInfrastructureReferenceModel = "IntegratedInfoInfrastructureReferenceModel"
    TechnicalReferenceModel = "TechnicalReferenceModel"



@dataclass(frozen=True)
class ArchitectureContract:
    """A real, typed container for the scope/criteria TOGAF Phase G's compliance review checks a deliverable against. Constructing this closes the TYPE gap only -- filling scope/criteria for a real deliverable, and the actual review verdict, remain separate, real work this class does not perform."""
    contract_criterion: tuple[str, ...] = ()  #  (ref: http://www.w3.org/2001/XMLSchema#string)
    contract_governance_role: tuple[str, ...] = ()  #  (ref: TogafGovernanceRole)
    contract_scope: tuple[str, ...] = ()  #  (ref: http://www.w3.org/2001/XMLSchema#string)


@dataclass(frozen=True)
class ChangeRequest:
    """A real, typed container for Phase H's 'develop change requirements to meet performance targets' step. Governance disposition (accepted/rejected/deferred) remains real, separate work -- this class only closes the type gap."""
    change_affected_requirement: tuple[str, ...] = ()  #  (ref: http://www.w3.org/2001/XMLSchema#string)
    change_approval_status: str | None = None  #  (ref: ApprovalStatus)
    change_description: tuple[str, ...] = ()  #  (ref: http://www.w3.org/2001/XMLSchema#string)


@dataclass(frozen=True)
class StatementOfArchitectureWork:
    """A real, typed container for Phase A's Statement of Architecture Work. Its approval_status field defaults to PendingHumanApproval -- constructing this object never itself grants approval; only an accountable human decision right can (per .claude/rules/fde-authority-boundary.md)."""
    sow_approval_status: str | None = None  #  (ref: ApprovalStatus)
    sow_scope: tuple[str, ...] = ()  #  (ref: http://www.w3.org/2001/XMLSchema#string)


__all__ = [
    "StandingValue",
    "ArchitectureContract",
    "ChangeRequest",
    "StatementOfArchitectureWork",
]
