# Chicago-style, no mocks: see .claude/rules/testing-chicago-style.md
"""Chicago-style test for the real, ggen-manufactured constitution module.

Exercises the real `autofde_lab.constitution.standing` module -- a direct
Python projection generated by `ggen sync run` from `ontology/standing.ttl`
-- with a real import and real object construction. No test doubles of any
kind substitute for a collaborator anywhere in this file: every assertion
below is against the real `StandingValue` enum and the real frozen
`Refusal` / `StandingAssertion` dataclasses as manufactured, and against the
real six-status vocabulary defined in `.claude/rules/standing-law.md`.
"""
from __future__ import annotations

import dataclasses
import enum

import pytest

from autofde_lab.constitution import standing


def test_real_import_succeeds():
    """The module import itself is the first real collaborator exercised."""
    assert standing.__name__ == "autofde_lab.constitution.standing"


def test_standing_value_is_enum_subclass():
    assert issubclass(standing.StandingValue, enum.Enum)


def test_standing_value_has_exactly_six_members_with_exact_string_values():
    members = standing.StandingValue

    # Exact member-name set: not more, not fewer than the six-status
    # vocabulary in .claude/rules/standing-law.md.
    expected_names = {
        "ALIVE",
        "BLOCKED",
        "BUILD_BROKEN",
        "PARTIAL_ALIVE",
        "UNKNOWN",
        "UNSUPPORTED",
    }
    actual_names = {member.name for member in members}
    assert actual_names == expected_names
    assert len(members) == 6

    # Exact string value of each member, asserted explicitly and individually.
    assert standing.StandingValue.ALIVE.value == "ALIVE"
    assert standing.StandingValue.BLOCKED.value == "BLOCKED"
    assert standing.StandingValue.BUILD_BROKEN.value == "BUILD_BROKEN"
    assert standing.StandingValue.PARTIAL_ALIVE.value == "PARTIAL_ALIVE"
    assert standing.StandingValue.UNKNOWN.value == "UNKNOWN"
    assert standing.StandingValue.UNSUPPORTED.value == "UNSUPPORTED"


def test_real_refusal_construction_and_fields():
    refusal = standing.Refusal(
        refusal_code=("NO_TYPED_VALID_PLAN",),
        refusal_reason=("environment model could not represent the constraint",),
    )

    assert refusal.refusal_code == ("NO_TYPED_VALID_PLAN",)
    assert refusal.refusal_reason == (
        "environment model could not represent the constraint",
    )


def test_real_standing_assertion_construction_and_fields():
    assertion = standing.StandingAssertion(
        derived_from_witness=("witness://episode/4b1d493441504091a6fb082b49d87937",),
        standing_subject="autofde_lab.constitution.standing",
        standing_value=standing.StandingValue.BLOCKED.value,
    )

    assert assertion.standing_value == "BLOCKED"
    assert assertion.standing_value == standing.StandingValue.BLOCKED.value
    assert assertion.standing_subject == "autofde_lab.constitution.standing"
    assert assertion.derived_from_witness == (
        "witness://episode/4b1d493441504091a6fb082b49d87937",
    )


def test_refusal_is_frozen_dataclass():
    assert dataclasses.is_dataclass(standing.Refusal)
    refusal = standing.Refusal(
        refusal_code=("BUILD_BROKEN",),
        refusal_reason=("collection failed",),
    )
    with pytest.raises(dataclasses.FrozenInstanceError):
        refusal.refusal_code = ("MUTATED",)  # type: ignore[misc]


def test_standing_assertion_is_frozen_dataclass():
    assert dataclasses.is_dataclass(standing.StandingAssertion)
    assertion = standing.StandingAssertion(
        derived_from_witness=(),
        standing_subject="tests/test_constitution_standing_chicago.py",
        standing_value=standing.StandingValue.UNKNOWN.value,
    )
    with pytest.raises(dataclasses.FrozenInstanceError):
        assertion.standing_value = standing.StandingValue.ALIVE.value  # type: ignore[misc]
