# Chicago-style, no mocks: see .claude/rules/testing-chicago-style.md
"""Chicago-style test for the real ggen-manufactured `autofde_lab.constitution.lab`.

Exercises the real dataclasses generated by `ggen sync run` into
`src/autofde_lab/constitution/lab.py` from the source ontology at
`ontology/lab.ttl`. No mocks anywhere -- no `unittest.mock`, `Mock`,
`MagicMock`, `patch`, or `monkeypatch`. Every name in `lab.__all__` is
resolved via `getattr`, constructed with real, explicit, representative
field values, and asserted against its real constructed state (not merely
"did it construct"). At least one class is also checked for the real
`dataclasses.FrozenInstanceError` that `@dataclass(frozen=True)` raises on
post-construction mutation.
"""

import dataclasses

import pytest

from autofde_lab.constitution import lab

# Representative, non-default field values for every dataclass in lab.__all__.
# Classes with no ontology-asserted fields (empty dataclasses) get an empty
# kwargs dict -- there is nothing to fill, not a shortcut around filling it.
REPRESENTATIVE_KWARGS = {
    "Capability": {},
    "Experiment": {},
    "Goal": {},
    "Gym": {"has_world": ("urn:example:1",)},
    "Invariant": {},
    "Perturbation": {"perturbs_world": ("urn:example:2",)},
    "Resource": {},
    "Trial": {"trial_id": "urn:example:trial-1"},
}


def test_real_import_succeeds():
    """`from autofde_lab.constitution import lab` is a real import, not stubbed."""
    assert lab.__all__ == [
        "Capability",
        "Experiment",
        "Goal",
        "Gym",
        "Invariant",
        "Perturbation",
        "Resource",
        "Trial",
    ]


def test_every_name_in___all___constructs_with_representative_values_and_matches_state():
    """For every name in lab.__all__, getattr the class, construct a real instance
    with representative values for every real field, and assert the constructed
    instance's real field values equal what was passed in.
    """
    assert set(REPRESENTATIVE_KWARGS) == set(lab.__all__)

    for name in lab.__all__:
        cls = getattr(lab, name)
        kwargs = REPRESENTATIVE_KWARGS[name]
        instance = cls(**kwargs)

        field_names = {f.name for f in dataclasses.fields(instance)}
        assert field_names == set(kwargs), (
            f"{name}: ontology fields {field_names!r} do not match the "
            f"representative kwargs {set(kwargs)!r} -- lab.py's real shape changed"
        )
        for field_name, expected_value in kwargs.items():
            assert getattr(instance, field_name) == expected_value


def test_gym_has_world_holds_the_real_tuple_of_strings():
    gym = lab.Gym(has_world=("urn:example:1", "urn:example:2"))
    assert gym.has_world == ("urn:example:1", "urn:example:2")
    assert isinstance(gym.has_world, tuple)
    assert all(isinstance(ref, str) for ref in gym.has_world)


def test_gym_has_world_defaults_to_empty_tuple_when_omitted():
    gym = lab.Gym()
    assert gym.has_world == ()


def test_perturbation_perturbs_world_holds_the_real_tuple_of_strings():
    perturbation = lab.Perturbation(perturbs_world=("urn:example:3",))
    assert perturbation.perturbs_world == ("urn:example:3",)


def test_trial_trial_id_holds_a_real_string():
    trial = lab.Trial(trial_id="urn:example:trial-42")
    assert trial.trial_id == "urn:example:trial-42"


def test_trial_trial_id_accepts_real_none():
    trial = lab.Trial(trial_id=None)
    assert trial.trial_id is None


def test_empty_dataclasses_have_no_ontology_fields():
    """Capability, Experiment, Goal, Invariant, Resource assert no required
    cardinality in ontology/lab.ttl and carry no fields in the manufactured
    projection -- confirm that shape is real, not assumed.
    """
    for name in ("Capability", "Experiment", "Goal", "Invariant", "Resource"):
        cls = getattr(lab, name)
        instance = cls()
        assert dataclasses.fields(instance) == ()
        assert isinstance(instance, cls)


def test_gym_is_a_real_frozen_dataclass_mutation_raises():
    """@dataclass(frozen=True) really raises FrozenInstanceError on mutation --
    verified against a class that has a real field.
    """
    gym = lab.Gym(has_world=("urn:example:1",))
    with pytest.raises(dataclasses.FrozenInstanceError):
        gym.has_world = ("urn:example:mutated",)
    # the original, real state must be untouched by the failed mutation attempt
    assert gym.has_world == ("urn:example:1",)


def test_trial_is_a_real_frozen_dataclass_mutation_raises():
    """Same real frozen-dataclass property, verified against a second class
    (str | None field) so the check isn't coincidental to tuple fields.
    """
    trial = lab.Trial(trial_id="urn:example:trial-1")
    with pytest.raises(dataclasses.FrozenInstanceError):
        trial.trial_id = "urn:example:mutated"
    assert trial.trial_id == "urn:example:trial-1"


def test_capability_is_a_real_frozen_dataclass_even_with_no_fields():
    """Frozen dataclasses reject attribute assignment unconditionally, not just
    for declared fields -- verify that holds even on a class with zero real
    ontology fields.
    """
    capability = lab.Capability()
    with pytest.raises(dataclasses.FrozenInstanceError):
        capability.some_attribute_not_declared_anywhere = "nope"
