# Chicago-style, no mocks: see .claude/rules/testing-chicago-style.md
"""Exercises the real ggen-manufactured module `autofde_lab.constitution.authority`.

No mocks, no stubs, no fakes: this test performs a real import of the manufactured
dataclasses and constructs real instances with every field explicitly filled, then
asserts on the real constructed state. The module itself is generated by `ggen sync
run` from `ontology/authority.ttl` (see the module's own docstring) -- this test is
the independently-runnable check that the generated shape still matches what the
ontology committed to.
"""
import dataclasses

import pytest

from autofde_lab.constitution import authority


def test_real_import_succeeds():
    """The module import itself is real -- no patching of sys.modules."""
    assert hasattr(authority, "__all__")
    assert authority.__all__ == ["Actuation", "AuthorityEnvelope"]


def test_actuation_real_fields_all_populated_with_representative_values():
    cls = getattr(authority, "Actuation")
    instance = cls(
        acts_on_environment=("urn:example:environment:1",),
        authorized_by="urn:example:authorityenvelope:1",
        exercises_capability=("urn:example:capability:1", "urn:example:capability:2"),
        realizes_commitment="urn:example:powlcommitment:1",
    )

    # Real state assertions on the real constructed instance -- not merely
    # "it constructed without raising".
    assert instance.acts_on_environment == ("urn:example:environment:1",)
    assert instance.authorized_by == "urn:example:authorityenvelope:1"
    assert instance.exercises_capability == (
        "urn:example:capability:1",
        "urn:example:capability:2",
    )
    assert instance.realizes_commitment == "urn:example:powlcommitment:1"

    # Field types match the ontology-derived shape: non-functional properties
    # are tuples of reference strings; functional properties are optional
    # single reference strings.
    assert isinstance(instance.acts_on_environment, tuple)
    assert all(isinstance(ref, str) for ref in instance.acts_on_environment)
    assert isinstance(instance.exercises_capability, tuple)
    assert isinstance(instance.authorized_by, str)
    assert isinstance(instance.realizes_commitment, str)


def test_actuation_is_frozen_and_mutation_raises():
    cls = getattr(authority, "Actuation")
    instance = cls(
        acts_on_environment=("urn:example:environment:1",),
        authorized_by="urn:example:authorityenvelope:1",
        exercises_capability=("urn:example:capability:1",),
        realizes_commitment="urn:example:powlcommitment:1",
    )

    with pytest.raises(dataclasses.FrozenInstanceError):
        instance.authorized_by = "urn:example:authorityenvelope:2"

    # The original real state is unchanged after the failed mutation attempt.
    assert instance.authorized_by == "urn:example:authorityenvelope:1"


def test_authority_envelope_real_fields_all_populated_with_representative_values():
    cls = getattr(authority, "AuthorityEnvelope")
    instance = cls(
        authority_capability=("urn:example:capability:1",),
        authority_subject=("urn:example:agent:1", "urn:example:agent:2"),
        authorizes_actuation=("urn:example:actuation:1",),
        single_use=("true",),
        valid_from=("2026-08-08T00:00:00Z",),
        valid_until=("2026-08-09T00:00:00Z",),
    )

    assert instance.authority_capability == ("urn:example:capability:1",)
    assert instance.authority_subject == ("urn:example:agent:1", "urn:example:agent:2")
    assert instance.authorizes_actuation == ("urn:example:actuation:1",)
    assert instance.single_use == ("true",)
    assert instance.valid_from == ("2026-08-08T00:00:00Z",)
    assert instance.valid_until == ("2026-08-09T00:00:00Z",)

    # All six declared fields on this dataclass are non-functional properties
    # per the module docstring, so every one renders as a tuple of reference
    # strings -- verify that shape holds for the real constructed instance.
    for field in dataclasses.fields(instance):
        value = getattr(instance, field.name)
        assert isinstance(value, tuple)
        assert all(isinstance(item, str) for item in value)


def test_authority_envelope_is_frozen_and_mutation_raises():
    cls = getattr(authority, "AuthorityEnvelope")
    instance = cls(
        authority_capability=("urn:example:capability:1",),
        authority_subject=("urn:example:agent:1",),
        authorizes_actuation=("urn:example:actuation:1",),
        single_use=("false",),
        valid_from=("2026-08-08T00:00:00Z",),
        valid_until=("2026-08-09T00:00:00Z",),
    )

    with pytest.raises(dataclasses.FrozenInstanceError):
        instance.single_use = ("true",)

    assert instance.single_use == ("false",)


def test_all_names_in___all___resolve_to_real_frozen_dataclasses():
    """Generic sweep over authority.__all__: every exported name is a real,
    constructible, frozen dataclass -- guards against __all__ drifting from
    the module's actual class definitions.
    """
    for name in authority.__all__:
        cls = getattr(authority, name)
        assert dataclasses.is_dataclass(cls)
        params = dataclasses.fields(cls)
        assert len(params) > 0

        # Construct with every field filled per its declared type.
        kwargs = {}
        for field in params:
            if field.type in ("tuple[str, ...]", "tuple[str,...]"):
                kwargs[field.name] = ("urn:example:1",)
            elif field.type in ("str | None", "Optional[str]"):
                kwargs[field.name] = "urn:example:functional:1"
            else:
                raise AssertionError(
                    f"unhandled field type {field.type!r} on {name}.{field.name} -- "
                    "extend this sweep, don't skip the field"
                )
        instance = cls(**kwargs)

        # Real state assertion: every field round-trips to what was passed.
        for field in params:
            assert getattr(instance, field.name) == kwargs[field.name]

        # Frozen dataclass instances refuse attribute assignment.
        first_field_name = params[0].name
        with pytest.raises(dataclasses.FrozenInstanceError):
            setattr(instance, first_field_name, getattr(instance, first_field_name))

