# Chicago-style, no mocks: see .claude/rules/testing-chicago-style.md
"""Exercises the real ggen-manufactured module ``autofde_lab.constitution.process``.

No mocks anywhere in this file: it performs a real import of the module, constructs
real instances of every dataclass named in ``process.__all__`` with every one of its
real fields explicitly filled with representative values, and asserts on the real
constructed instance's real field values (never on "was it constructed" alone).
``src/autofde_lab/constitution/process.py`` is GENERATED by ``ggen sync run`` from
the source ontology file ``ontology/process.ttl`` -- see that module's own docstring
for the manufacture provenance. This test treats the manufactured module as ordinary
source and exercises it directly; it does not touch the ontology or the generator.
"""
from __future__ import annotations

import dataclasses

import pytest

from autofde_lab.constitution import process


def test_real_import_succeeds_and_dunder_all_matches_known_manifest() -> None:
    """The real import succeeds, and ``__all__`` is exactly the manufactured
    classes read directly from the source file (no guessing) -- extended
    2026-08-10 with ``Activity``/``Guard``/``StandingValue`` after
    ``ontology/process.ttl`` gained the ``afl:Activity``/``afl:Guard``
    classes and the ``afl:ConsequenceClass`` (PURE/READ/DO/VERIFY) named
    individuals, regenerated via a real ``ggen sync run``."""
    assert process.__all__ == [
        "StandingValue",
        "Activity",
        "ChoiceGraph",
        "Guard",
        "OrderEdge",
        "POWLCommitment",
        "POWLProcess",
        "PartialOrderComposite",
        "ProcessNode",
        "SilentTransition",
        "TransitionNode",
    ]


def test_standing_value_enum_carries_the_four_consequence_classes() -> None:
    """The manufactured ``StandingValue`` enum (the shared template's own
    name for any vocabulary-individual block, per
    ``templates/constitution_module.py.tera``) carries exactly the four
    named individuals ``ontology/process.ttl``'s ``afl:ConsequenceScheme``
    declares -- PURE/READ/DO/VERIFY, real activity-consequence classes, not
    guessed values."""
    assert {member.value for member in process.StandingValue} == {"PURE", "READ", "DO", "VERIFY"}


def test_activity_dataclass_has_the_real_ontology_fields() -> None:
    cls = process.Activity
    instance = cls(
        estimated_cost="urn:example:cost-1",
        expected_information_gain="urn:example:gain-1",
        has_consequence="urn:example:DO",
        required_capability_class="urn:example:capability-class-1",
    )
    assert instance.estimated_cost == "urn:example:cost-1"
    assert instance.expected_information_gain == "urn:example:gain-1"
    assert instance.has_consequence == "urn:example:DO"
    assert instance.required_capability_class == "urn:example:capability-class-1"


def test_guard_dataclass_has_the_real_ontology_fields() -> None:
    cls = process.Guard
    instance = cls(guard_predicate="causal_closure", guards_edge="urn:example:edge-1")
    assert instance.guard_predicate == "causal_closure"
    assert instance.guards_edge == "urn:example:edge-1"


def test_powl_commitment_and_powl_process_class_names_render_with_correct_casing() -> None:
    """ggen manufacture must render POWL's internal acronym casing correctly and
    never mangle it into "Powlcommitment"/"Powlprocess"."""
    assert process.POWLCommitment.__name__ == "POWLCommitment"
    assert process.POWLProcess.__name__ == "POWLProcess"


def test_choice_graph_constructs_with_no_fields() -> None:
    cls = getattr(process, "ChoiceGraph")
    instance = cls()
    assert isinstance(instance, process.ChoiceGraph)
    assert dataclasses.fields(instance) == ()


def test_silent_transition_constructs_with_no_fields() -> None:
    cls = getattr(process, "SilentTransition")
    instance = cls()
    assert isinstance(instance, process.SilentTransition)
    assert dataclasses.fields(instance) == ()


def test_transition_node_constructs_with_no_fields() -> None:
    cls = getattr(process, "TransitionNode")
    instance = cls()
    assert isinstance(instance, process.TransitionNode)
    assert dataclasses.fields(instance) == ()


def test_order_edge_all_fields_explicit() -> None:
    cls = getattr(process, "OrderEdge")
    instance = cls(
        after_node="urn:example:node-2",
        before_node="urn:example:node-1",
    )
    assert instance.after_node == "urn:example:node-2"
    assert instance.before_node == "urn:example:node-1"


def test_powl_commitment_all_fields_explicit() -> None:
    cls = getattr(process, "POWLCommitment")
    instance = cls(
        commits_to="urn:example:governed-candidate-1",
        committed_process="urn:example:powl-process-1",
    )
    assert instance.commits_to == "urn:example:governed-candidate-1"
    assert instance.committed_process == "urn:example:powl-process-1"


def test_powl_process_all_fields_explicit() -> None:
    cls = getattr(process, "POWLProcess")
    instance = cls(
        has_root_node="urn:example:root-node-1",
        preserves_node=("urn:example:node-1", "urn:example:node-2"),
        repair_of=("urn:example:powl-process-0",),
    )
    assert instance.has_root_node == "urn:example:root-node-1"
    assert instance.preserves_node == ("urn:example:node-1", "urn:example:node-2")
    assert instance.repair_of == ("urn:example:powl-process-0",)


def test_partial_order_composite_all_fields_explicit() -> None:
    cls = getattr(process, "PartialOrderComposite")
    instance = cls(has_order_edge=("urn:example:order-edge-1", "urn:example:order-edge-2"))
    assert instance.has_order_edge == ("urn:example:order-edge-1", "urn:example:order-edge-2")


def test_process_node_all_fields_explicit() -> None:
    cls = getattr(process, "ProcessNode")
    instance = cls(
        affected_by_perturbation=("urn:example:perturbation-1",),
        has_child_node=("urn:example:node-child-1", "urn:example:node-child-2"),
        precedes=("urn:example:node-successor-1",),
    )
    assert instance.affected_by_perturbation == ("urn:example:perturbation-1",)
    assert instance.has_child_node == ("urn:example:node-child-1", "urn:example:node-child-2")
    assert instance.precedes == ("urn:example:node-successor-1",)


def test_every_name_in_dunder_all_resolves_via_getattr_and_constructs() -> None:
    """Generic sweep over ``process.__all__``: every DATACLASS name resolves
    via ``getattr`` to a real dataclass, gets constructed with representative
    values for every one of its real fields (discovered from
    ``dataclasses.fields``, not hardcoded per class), and the constructed
    instance's real field values round-trip exactly. ``StandingValue`` (the
    manufactured vocabulary enum, not a dataclass) is swept separately below
    rather than skipped silently."""
    representative_values = {
        "after_node": "urn:example:after-node-1",
        "before_node": "urn:example:before-node-1",
        "commits_to": "urn:example:governed-candidate-1",
        "committed_process": "urn:example:powl-process-1",
        "has_root_node": "urn:example:root-node-1",
        "preserves_node": ("urn:example:preserved-node-1",),
        "repair_of": ("urn:example:repaired-process-1",),
        "has_order_edge": ("urn:example:order-edge-1",),
        "affected_by_perturbation": ("urn:example:perturbation-1",),
        "has_child_node": ("urn:example:child-node-1",),
        "precedes": ("urn:example:successor-node-1",),
        "estimated_cost": "urn:example:cost-1",
        "expected_information_gain": "urn:example:gain-1",
        "has_consequence": "urn:example:DO",
        "required_capability_class": "urn:example:capability-class-1",
        "guard_predicate": "urn:example:causal-closure",
        "guards_edge": "urn:example:edge-1",
    }
    checked_classes = []
    for name in process.__all__:
        cls = getattr(process, name)
        if not dataclasses.is_dataclass(cls):
            continue
        field_names = [f.name for f in dataclasses.fields(cls)]
        kwargs = {fname: representative_values[fname] for fname in field_names}
        instance = cls(**kwargs)
        for fname, value in kwargs.items():
            assert getattr(instance, fname) == value
        checked_classes.append(name)
    assert checked_classes == [n for n in process.__all__ if n != "StandingValue"]


def test_dataclasses_are_frozen_mutation_raises_frozen_instance_error() -> None:
    """Attempting to mutate a field on a constructed instance raises the real
    ``dataclasses.FrozenInstanceError`` -- verified for both ``POWLCommitment`` and
    ``OrderEdge``."""
    commitment = process.POWLCommitment(
        commits_to="urn:example:governed-candidate-1",
        committed_process="urn:example:powl-process-1",
    )
    with pytest.raises(dataclasses.FrozenInstanceError):
        commitment.commits_to = "urn:example:mutated"  # type: ignore[misc]
    # The instance is unchanged after the failed mutation attempt.
    assert commitment.commits_to == "urn:example:governed-candidate-1"

    edge = process.OrderEdge(after_node="urn:example:a", before_node="urn:example:b")
    with pytest.raises(dataclasses.FrozenInstanceError):
        edge.after_node = "urn:example:mutated"  # type: ignore[misc]
    assert edge.after_node == "urn:example:a"
