"""World-transformation scenario fixtures — direct Python projection.

Manufactured by `ggen sync run` from `ontology/world-transformation-taxonomy.ttl`
via `queries/world-transformation/scenario_projection.rq`: one fixture
function per real `afl:WorldTransformationScenario` individual, each
returning a real, admitted `autofde_lab.powl.algebra.ChoiceGraph`:

    Start -> observe -> infer_desired_state -> compute_delta
          -> select_transformation -> manufacture -> verify -> End

This is the wider frame a scenario carries: current state + objectives +
constraints + authority -> inferred desired state -> semantic delta ->
candidate transformation -> manufactured system -> independent
verification. Debugging (the narrower `k8s_fault_universes.py` shape:
`observe -> hypothesize -> diagnose -> remediate`) is the special case
where the desired state is already known and the delta is a deviation to
restore.

Schema and worked-example fixtures only. `infer_desired_state`,
`compute_delta`, `select_transformation`, `manufacture`, and `verify` are
inert `Atom`s here, exactly like `remediate` already is in
`k8s_fault_universes.py` -- no live LLM inference, no delta computation, no
planner-portfolio wiring, no actuation. Additive only -- not wired into
`SreTroubleshootingDecisionBackend`, the breed ensemble, or the planner
federation, matching every other ggen-manufactured module in this repo.

Never reads, imports, or subprocesses `vendor/gyms/sregym` (see
`.claude/rules/gym-actuation-boundary.md`) -- every scenario's numbers are
authored directly in `ontology/world-transformation-taxonomy.ttl`.

GENERATED by ggen. DO NOT EDIT BY HAND -- edit
`ontology/world-transformation-taxonomy.ttl` and re-run `ggen sync run`
from the repo root to regenerate.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable

from autofde_lab.powl.algebra import (
    Atom,
    ChoiceGraph,
    ChoiceGraphEdge,
    End,
    NodeId,
    Start,
)


@dataclass(frozen=True)
class ScenarioMetadata_checkout_latency_scenario_v_1:
    """Real observed/objective/constraint values for `CheckoutLatencyScenario_v1`, threaded through as plain Python values (not only Atom labels)."""

    observations: dict[str, float] = field(default_factory=lambda: {
        "api_instance_count": 3,
        "db_publicly_reachable": 1,
        "failure_budget_exhausted": 1,
        "p95_latency_ms": 780,
        "sql_primary_count": 1,
    })
    objectives: tuple[dict, ...] = field(default_factory=lambda: (
        {"kind": "AvailabilityTarget", "comparator": "GreaterThanOrEqual", "threshold": 99.9, "unit": "percent"},
        {"kind": "LatencySLO", "comparator": "LessThan", "threshold": 250, "unit": "ms"},
    ))
    constraints: tuple[dict, ...] = field(default_factory=lambda: (
        {"kind": "DataResidency", "comparator": "", "threshold": None, "unit": "", "note": "customer data must remain private"},
        {"kind": "DataResidency", "comparator": "", "threshold": None, "unit": "", "note": "no cross-region requirement"},
        {"kind": "CostCeiling", "comparator": "LessThan", "threshold": 18000, "unit": "usd_per_month", "note": ""},
    ))


def scenario_checkout_latency_scenario_v_1() -> ChoiceGraph:
    """World-transformation scenario `CheckoutLatencyScenario_v1`: observe -> infer_desired_state -> compute_delta -> select_transformation -> manufacture -> verify."""
    observe = Atom(label="observe_checkout_latency_scenario_v_1", consequence="READ")
    infer_desired_state = Atom(label="infer_desired_state_checkout_latency_scenario_v_1", consequence="PURE")
    compute_delta = Atom(label="compute_delta_checkout_latency_scenario_v_1", consequence="PURE")
    select_transformation = Atom(label="select_transformation_checkout_latency_scenario_v_1", consequence="PURE")
    manufacture = Atom(label="manufacture_checkout_latency_scenario_v_1", consequence="DO")
    verify = Atom(label="verify_checkout_latency_scenario_v_1", consequence="VERIFY")
    return ChoiceGraph(
        children=(Start(), End(), observe, infer_desired_state, compute_delta, select_transformation, manufacture, verify),
        edges=frozenset(
            [
                ChoiceGraphEdge(NodeId(0), NodeId(2)),
                ChoiceGraphEdge(NodeId(2), NodeId(3)),
                ChoiceGraphEdge(NodeId(3), NodeId(4)),
                ChoiceGraphEdge(NodeId(4), NodeId(5)),
                ChoiceGraphEdge(NodeId(5), NodeId(6)),
                ChoiceGraphEdge(NodeId(6), NodeId(7)),
                ChoiceGraphEdge(NodeId(7), NodeId(1)),
            ]
        ),
        start=0,
        end=1,
    )

__all__ = [
    "scenario_checkout_latency_scenario_v_1",
    "ScenarioMetadata_checkout_latency_scenario_v_1",
]
