"""GENERATED by ggen from planner-league.ttl + autofde-lab-capabilities.ttl.

Do not hand-edit. Planner inventory is projected from the live generated
capability ontology; DSPyPolicy is separated as a novelty-boundary oracle.
"""

PRIMARY_PLANNERS = (
    "AOstar",
    "Astar",
    "AugmentedRandomSearch",
    "BFWS",
    "CGP",
    "CIDual",
    "DESPOT",
    "DOSolver",
    "EHC",
    "FF",
    "FFDetHindsight",
    "FFReplan",
    "FRET",
    "GPCI",
    "GPHH",
    "GoalHSVI",
    "HSVI",
    "IDAstar",
    "IDual",
    "ILAOstar",
    "IW",
    "LDFS",
    "LRTAstar",
    "LRTDP",
    "MAHD",
    "MARTDP",
    "MCTS",
    "MDPLP",
    "MaxentIRL",
    "PI",
    "POMCP",
    "PPDDLDetHindsight",
    "PPDDLPlanMerger",
    "PPDDLReplan",
    "PilePolicy",
    "RDDLGurobiSolver",
    "RDDLJaxSolver",
    "RFF",
    "RIW",
    "RTDPBel",
    "RayRLlib",
    "SARSOP",
    "SSPDetHindsight",
    "SSPLP",
    "SSPPlanMerger",
    "SSPReplan",
    "SSiPP",
    "SimpleGreedy",
    "StableBaseline",
    "UCT",
    "UPSolver",
    "VI",
    "Witness",
    "pAstar",
    "pLRTAstar",
    "pPOMCP",
)
NOVELTY_ORACLES = ("DSPyPolicy",)
PLANNER_CAPABILITY_FIELDS = (
    "action_representation",
    "completeness_guarantee",
    "deterministic_stochastic",
    "domains",
    "expected_complexity_class",
    "full_partial_observability",
    "latency_envelope",
    "memory_envelope",
    "numeric_support",
    "offline_online",
    "optimality_guarantee",
    "parameter_schema",
    "plan_output_type",
    "planner_id",
    "planning_horizon",
    "refusal_conditions",
    "resource_constraints",
    "single_multi_agent",
    "state_representation",
    "temporal_support",
)
ROLE_SPECS = {
    "assumption_falsifier": {
        "objective": "find_minimal_observation_failure",
        "action_projection": "information_partition_intent",
    },
    "blue_defender": {
        "objective": "restore_and_preserve_service",
        "action_projection": "candidate_plan",
    },
    "capacity_planner": {
        "objective": "satisfy_capacity_under_budget",
        "action_projection": "candidate_plan",
    },
    "enterprise_architect": {
        "objective": "maximize_reversible_enterprise_fit",
        "action_projection": "candidate_plan",
    },
    "incident_commander": {
        "objective": "minimize_incident_consequence",
        "action_projection": "candidate_plan",
    },
    "logistics_coordinator": {
        "objective": "minimize_flow_cost",
        "action_projection": "candidate_plan",
    },
    "plan_constructor": {
        "objective": "construct_goal_reaching_plan",
        "action_projection": "candidate_plan",
    },
    "plan_falsifier": {
        "objective": "find_plan_counterexample",
        "action_projection": "falsification_intent",
    },
    "red_disturbance": {
        "objective": "manufacture_admitted_disturbance",
        "action_projection": "disturbance_intent",
    },
    "reward_falsifier": {
        "objective": "find_reward_specification_failure",
        "action_projection": "falsification_intent",
    },
    "sre_recovery": {
        "objective": "minimize_recovery_loss",
        "action_projection": "candidate_plan",
    },
    "world_model_falsifier": {
        "objective": "find_minimal_ranking_reversal",
        "action_projection": "world_mutation_intent",
    },
}
WORLD_CLASSES = (
    "cyber_incident",
    "generic_enterprise",
    "identity_degradation",
    "mission_critical_dependency",
)
OBSERVATION_PROJECTIONS = (
    "full_observation",
    "partial_observation",
    "stale_observation",
)
ACTION_PROJECTIONS = (
    "candidate_plan",
    "disturbance_intent",
    "falsification_intent",
    "information_partition_intent",
    "world_mutation_intent",
)
BUDGETS = (
    "balanced",
    "deep_search",
    "latency_tight",
)
EXPERIMENT_DIMENSIONS = (
    "budget",
    "objective",
    "observation",
    "opponent_planner",
    "opponent_role",
    "planner",
    "role",
    "world",
)
