"""Fortune-5-scale combinatorial enterprise exploration surface."""

from .catalog import AXES, CATALOG_ROWS
from .enterprise_architecture import (
    ADVISORY,
    FORTUNE5_EA_REQUIREMENTS,
    MANDATORY,
    PUBLIC_INTERCHANGE_ALIGNMENT,
    REQUIRED_ARCHITECTURE_VIEWS,
    REQUIRED_REFERENCE_ARTIFACTS,
    ArchitectureRequirement,
    EnterpriseArchitecturePackage,
    EnterpriseArchitectureProfile,
    EnterpriseArchitectureSubmission,
    EnterpriseArchitectureVerifier,
    EnterpriseArchitectureWitness,
    ExceptionEvidence,
    RequirementEvidence,
    TransitionPlan,
    architecture_artifact_digest,
    build_enterprise_profile,
)
from .f5bench import (
    BenchmarkMutation,
    ResynchronizationWitness,
    architecture_optionality_density,
    verify_resynchronization,
)
from .readiness import (
    REQUIRED_GATES,
    F5ReadinessVerifier,
    GateEvidence,
    ReadinessSubmission,
    ReadinessWitness,
    build_submission,
    evidence_digest,
    failure_rate,
    reference_profile_digest,
    subject_identity_digest,
)
from .space import (
    Axis,
    CompatibilityLaw,
    Option,
    Scenario,
    StateSpace,
    pairwise_covering,
    pairwise_token_count,
)

FORTUNE5_SPACE = StateSpace(axes=AXES)

__all__ = [
    "ADVISORY",
    "AXES",
    "CATALOG_ROWS",
    "FORTUNE5_EA_REQUIREMENTS",
    "FORTUNE5_SPACE",
    "MANDATORY",
    "PUBLIC_INTERCHANGE_ALIGNMENT",
    "REQUIRED_ARCHITECTURE_VIEWS",
    "REQUIRED_GATES",
    "REQUIRED_REFERENCE_ARTIFACTS",
    "ArchitectureRequirement",
    "Axis",
    "BenchmarkMutation",
    "CompatibilityLaw",
    "EnterpriseArchitecturePackage",
    "EnterpriseArchitectureProfile",
    "EnterpriseArchitectureSubmission",
    "EnterpriseArchitectureVerifier",
    "EnterpriseArchitectureWitness",
    "ExceptionEvidence",
    "F5ReadinessVerifier",
    "GateEvidence",
    "Option",
    "ReadinessSubmission",
    "ReadinessWitness",
    "RequirementEvidence",
    "ResynchronizationWitness",
    "Scenario",
    "StateSpace",
    "TransitionPlan",
    "architecture_artifact_digest",
    "architecture_optionality_density",
    "build_enterprise_profile",
    "build_submission",
    "evidence_digest",
    "failure_rate",
    "pairwise_covering",
    "pairwise_token_count",
    "reference_profile_digest",
    "subject_identity_digest",
    "verify_resynchronization",
]
