"""GENERATED by ggen from ontology/enterprise-architecture.ttl -- do not hand-edit."""

from __future__ import annotations

_ROWS = (
    ("principle", "EvidenceBoundedPrinciple", "EvidenceBounded"),
    ("principle", "NoSelfCertificationPrinciple", "NoSelfCertification"),
    (
        "principle",
        "OrganizationalStandingExternalPrinciple",
        "OrganizationalStandingExternal",
    ),
    (
        "principle",
        "ReversibleBeforeIrreversiblePrinciple",
        "ReversibleBeforeIrreversible",
    ),
    ("principle", "ZeroUnreceiptedActuationPrinciple", "ZeroUnreceiptedActuation"),
    ("requirement_kind", "AuthorityPolicyRequirement", "AuthorityPolicy"),
    ("requirement_kind", "AvailabilitySLORequirement", "AvailabilitySLO"),
    ("requirement_kind", "BusinessObjectiveRequirement", "BusinessObjective"),
    ("requirement_kind", "CapacityRequirement", "Capacity"),
    ("requirement_kind", "ChangeWindowRequirement", "ChangeWindow"),
    ("requirement_kind", "ComplianceControlRequirement", "ComplianceControl"),
    ("requirement_kind", "CostCeilingRequirement", "CostCeiling"),
    ("requirement_kind", "DataResidencyRequirement", "DataResidency"),
    ("requirement_kind", "LatencySLORequirement", "LatencySLO"),
    ("requirement_kind", "MigrationDeadlineRequirement", "MigrationDeadline"),
    ("requirement_kind", "RPORequirement", "RPO"),
    ("requirement_kind", "RTORequirement", "RTO"),
    ("requirement_kind", "SecurityControlRequirement", "SecurityControl"),
    ("requirement_kind", "VendorDependencyRequirement", "VendorDependency"),
    ("risk_class", "ComplianceRisk", "Compliance"),
    ("risk_class", "DataRisk", "Data"),
    ("risk_class", "FinancialRisk", "Financial"),
    ("risk_class", "MigrationRisk", "Migration"),
    ("risk_class", "OperationalRisk", "Operational"),
    ("risk_class", "ResilienceRisk", "Resilience"),
    ("risk_class", "SecurityRisk", "Security"),
    ("risk_class", "VendorRisk", "Vendor"),
    ("viewpoint", "ApplicationViewpoint", "Application"),
    ("viewpoint", "BusinessViewpoint", "Business"),
    ("viewpoint", "ComplianceViewpoint", "Compliance"),
    ("viewpoint", "DataViewpoint", "Data"),
    ("viewpoint", "FinOpsViewpoint", "FinOps"),
    ("viewpoint", "GovernanceViewpoint", "Governance"),
    ("viewpoint", "OperationsViewpoint", "Operations"),
    ("viewpoint", "ResilienceViewpoint", "Resilience"),
    ("viewpoint", "SecurityViewpoint", "Security"),
    ("viewpoint", "TechnologyViewpoint", "Technology"),
)

ENTERPRISE_VIEWPOINTS = {
    identifier: label
    for category, identifier, label in _ROWS
    if category == "viewpoint"
}
ENTERPRISE_REQUIREMENT_KINDS = {
    identifier: label
    for category, identifier, label in _ROWS
    if category == "requirement_kind"
}
ENTERPRISE_RISK_CLASSES = {
    identifier: label
    for category, identifier, label in _ROWS
    if category == "risk_class"
}
ENTERPRISE_ARCHITECTURE_PRINCIPLES = {
    identifier: label
    for category, identifier, label in _ROWS
    if category == "principle"
}

__all__ = [
    "ENTERPRISE_VIEWPOINTS",
    "ENTERPRISE_REQUIREMENT_KINDS",
    "ENTERPRISE_RISK_CLASSES",
    "ENTERPRISE_ARCHITECTURE_PRINCIPLES",
]
