"""AutoFDE Lab semantic constitution — direct Python projection.

Manufactured by `ggen sync run` from an ontology/*.ttl file in the merged
working-backwards Lab constitution (PR #37). Manufacture is provenance, not
architecture (ontology/manufacture.ttl) -- this is ordinary source at its
ordinary import path, additive only, and is not wired into any existing
runtime code path (no planner, no level4_crown, no gymact bridge imports it).

Object-property fields hold an identity-reference string (the referenced
object's own identity), never a resolved object -- this is a thin semantic
projection, not an ORM. Non-functional properties render as a tuple of
reference strings; functional properties render as an optional single
reference string. The ontology asserts no required cardinality anywhere, so
every field defaults to empty/None rather than being required.

GENERATED by ggen. DO NOT EDIT BY HAND -- edit the source ontology/*.ttl file
and re-run `ggen sync run` from the repo root to regenerate.
"""
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum



@dataclass(frozen=True)
class Actuation:
    """A consequential transition in an external or simulated world. Capability to perform it is not authority to perform it."""
    acts_on_environment: tuple[str, ...] = ()  #  (ref: Environment)
    authorized_by: str | None = None  #  (ref: AuthorityEnvelope)
    exercises_capability: tuple[str, ...] = ()  #  (ref: Capability)
    realizes_commitment: str | None = None  #  (ref: POWLCommitment)


@dataclass(frozen=True)
class AuthorityEnvelope:
    """A bounded grant associated with an exact subject, capability, scope, and consequential transition."""
    authority_capability: tuple[str, ...] = ()  #  (ref: Capability)
    authority_subject: tuple[str, ...] = ()  #  (ref: http://www.w3.org/ns/prov#Agent)
    authorizes_actuation: tuple[str, ...] = ()  #  (ref: Actuation)
    single_use: tuple[str, ...] = ()  #  (ref: http://www.w3.org/2001/XMLSchema#boolean)
    valid_from: tuple[str, ...] = ()  #  (ref: http://www.w3.org/2001/XMLSchema#dateTime)
    valid_until: tuple[str, ...] = ()  #  (ref: http://www.w3.org/2001/XMLSchema#dateTime)


__all__ = [
    "Actuation",
    "AuthorityEnvelope",
]
