"""AutoFDE Lab semantic constitution — direct Python projection.

Manufactured by `ggen sync run` from an ontology/*.ttl file in the merged
working-backwards Lab constitution (PR #37). Manufacture is provenance, not
architecture (ontology/manufacture.ttl) -- this is ordinary source at its
ordinary import path, additive only, and is not wired into any existing
runtime code path (no planner, no level4_crown, no gymact bridge imports it).

Object-property fields hold an identity-reference string (the referenced
object's own identity), never a resolved object -- this is a thin semantic
projection, not an ORM. Non-functional properties render as a tuple of
reference strings; functional properties render as an optional single
reference string. The ontology asserts no required cardinality anywhere, so
every field defaults to empty/None rather than being required.

GENERATED by ggen. DO NOT EDIT BY HAND -- edit the source ontology/*.ttl file
and re-run `ggen sync run` from the repo root to regenerate.
"""
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum



@dataclass(frozen=True)
class Artifact:
    """Artifact"""


@dataclass(frozen=True)
class ArtifactManifest:
    """Binds explicit artifact identities and digests to a trial and exact source/dependency revisions. Filenames are never sufficient identity."""
    binds_entity: tuple[str, ...] = ()  # Explicit identity binding for an entity participating in a witness. (ref: http://www.w3.org/ns/prov#Entity)
    dependency_revision: tuple[str, ...] = ()  #  (ref: DependencyRevision)
    manifests_artifact: tuple[str, ...] = ()  #  (ref: Artifact)
    source_revision: tuple[str, ...] = ()  #  (ref: SourceRevision)


@dataclass(frozen=True)
class DependencyRevision:
    """DependencyRevision"""


@dataclass(frozen=True)
class EvidenceWitness:
    """EvidenceWitness"""
    actuation: str | None = None  #  (ref: Actuation)
    authority: str | None = None  #  (ref: AuthorityEnvelope)
    commitment: str | None = None  #  (ref: POWLCommitment)
    derived_by_verifier: str | None = None  #  (ref: VerifierRun)
    governed_candidate: str | None = None  #  (ref: GovernedCandidate)
    manifest: str | None = None  #  (ref: ArtifactManifest)
    postcondition_observation: str | None = None  #  (ref: PostconditionObservation)
    receipt_dag: str | None = None  #  (ref: ReceiptDAG)
    replay: str | None = None  #  (ref: Replay)
    witness_for: str | None = None  #  (ref: Trial)


@dataclass(frozen=True)
class Level4Witness:
    """A fully joined identity-preserving witness whose standing can be independently reconstructed from persisted evidence."""


@dataclass(frozen=True)
class Observer:
    """Observer"""


@dataclass(frozen=True)
class Postcondition:
    """Postcondition"""


@dataclass(frozen=True)
class PostconditionObservation:
    """PostconditionObservation"""
    asserts_postcondition: tuple[str, ...] = ()  #  (ref: Postcondition)
    observes_actuation: str | None = None  #  (ref: Actuation)
    performed_by: str | None = None  #  (ref: Observer)


@dataclass(frozen=True)
class Receipt:
    """Receipt"""
    caused_by_receipt: tuple[str, ...] = ()  #  (ref: Receipt)
    evidences_actuation: tuple[str, ...] = ()  #  (ref: Actuation)
    evidences_observation: tuple[str, ...] = ()  #  (ref: PostconditionObservation)


@dataclass(frozen=True)
class ReceiptDAG:
    """ReceiptDAG"""
    contains_receipt: tuple[str, ...] = ()  #  (ref: Receipt)


@dataclass(frozen=True)
class Replay:
    """Replay"""
    replay_of_trial: str | None = None  #  (ref: Trial)
    replays_receipt: tuple[str, ...] = ()  #  (ref: Receipt)


@dataclass(frozen=True)
class SourceRevision:
    """SourceRevision"""


@dataclass(frozen=True)
class VerifierRun:
    """VerifierRun"""
    reads_manifest: tuple[str, ...] = ()  #  (ref: ArtifactManifest)


__all__ = [
    "Artifact",
    "ArtifactManifest",
    "DependencyRevision",
    "EvidenceWitness",
    "Level4Witness",
    "Observer",
    "Postcondition",
    "PostconditionObservation",
    "Receipt",
    "ReceiptDAG",
    "Replay",
    "SourceRevision",
    "VerifierRun",
]
