"""AutoFDE Lab semantic constitution — direct Python projection.

Manufactured by `ggen sync run` from an ontology/*.ttl file in the merged
working-backwards Lab constitution (PR #37). Manufacture is provenance, not
architecture (ontology/manufacture.ttl) -- this is ordinary source at its
ordinary import path, additive only, and is not wired into any existing
runtime code path (no planner, no level4_crown, no gymact bridge imports it).

Object-property fields hold an identity-reference string (the referenced
object's own identity), never a resolved object -- this is a thin semantic
projection, not an ORM. Non-functional properties render as a tuple of
reference strings; functional properties render as an optional single
reference string. The ontology asserts no required cardinality anywhere, so
every field defaults to empty/None rather than being required.

GENERATED by ggen. DO NOT EDIT BY HAND -- edit the source ontology/*.ttl file
and re-run `ggen sync run` from the repo root to regenerate.
"""
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum



@dataclass(frozen=True)
class ExternalRepresentation:
    """ExternalRepresentation"""


@dataclass(frozen=True)
class InteropAdapter:
    """InteropAdapter"""
    uses_contract: tuple[str, ...] = ()  #  (ref: InteropContract)


@dataclass(frozen=True)
class InteropContract:
    """InteropContract"""
    targets_representation: tuple[str, ...] = ()  #  (ref: ExternalRepresentation)


@dataclass(frozen=True)
class InteropContractReceipt:
    """Binds an adapter to the exact external repository/API contract and revision used as its oracle."""
    adapter_revision: tuple[str, ...] = ()  #  (ref: SourceRevision)
    contract_receipt_for: tuple[str, ...] = ()  #  (ref: InteropContract)
    external_revision: tuple[str, ...] = ()  #  (ref: DependencyRevision)


@dataclass(frozen=True)
class LossReport:
    """LossReport"""
    loss_report_for: tuple[str, ...] = ()  #  (ref: Projection)
    reports_loss: tuple[str, ...] = ()  #  (ref: SemanticLoss)
    semantics_preserved: tuple[str, ...] = ()  #  (ref: http://www.w3.org/2001/XMLSchema#boolean)


@dataclass(frozen=True)
class Projection:
    """Projection"""
    produced_by_adapter: tuple[str, ...] = ()  #  (ref: InteropAdapter)
    projects_representation: tuple[str, ...] = ()  #  (ref: ExternalRepresentation)


@dataclass(frozen=True)
class SemanticLoss:
    """SemanticLoss"""


__all__ = [
    "ExternalRepresentation",
    "InteropAdapter",
    "InteropContract",
    "InteropContractReceipt",
    "LossReport",
    "Projection",
    "SemanticLoss",
]
