"""AutoFDE Lab semantic constitution — direct Python projection.

Manufactured by `ggen sync run` from an ontology/*.ttl file in the merged
working-backwards Lab constitution (PR #37). Manufacture is provenance, not
architecture (ontology/manufacture.ttl) -- this is ordinary source at its
ordinary import path, additive only, and is not wired into any existing
runtime code path (no planner, no level4_crown, no gymact bridge imports it).

Object-property fields hold an identity-reference string (the referenced
object's own identity), never a resolved object -- this is a thin semantic
projection, not an ORM. Non-functional properties render as a tuple of
reference strings; functional properties render as an optional single
reference string. The ontology asserts no required cardinality anywhere, so
every field defaults to empty/None rather than being required.

GENERATED by ggen. DO NOT EDIT BY HAND -- edit the source ontology/*.ttl file
and re-run `ggen sync run` from the repo root to regenerate.
"""
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum



@dataclass(frozen=True)
class Capability:
    """Something the system can do. Capability does not imply authority."""


@dataclass(frozen=True)
class Experiment:
    """Experiment"""


@dataclass(frozen=True)
class Goal:
    """Goal"""


@dataclass(frozen=True)
class Gym:
    """A bounded consequential world with observable state, capabilities, authority, goals/invariants, lawful transitions, verification, and evidence."""
    has_world: tuple[str, ...] = ()  #  (ref: World)


@dataclass(frozen=True)
class Invariant:
    """Invariant"""


@dataclass(frozen=True)
class Perturbation:
    """A change to the world used to test adaptation, repair, or replanning."""
    perturbs_world: tuple[str, ...] = ()  #  (ref: World)


@dataclass(frozen=True)
class Resource:
    """Resource"""


@dataclass(frozen=True)
class Trial:
    """One identity-bounded experimental episode. Evidence from different trials must never satisfy one witness."""
    trial_id: str | None = None  #  (ref: http://www.w3.org/2001/XMLSchema#string)


__all__ = [
    "Capability",
    "Experiment",
    "Goal",
    "Gym",
    "Invariant",
    "Perturbation",
    "Resource",
    "Trial",
]
