"""AutoFDE Lab semantic constitution — direct Python projection.

Manufactured by `ggen sync run` from an ontology/*.ttl file in the merged
working-backwards Lab constitution (PR #37). Manufacture is provenance, not
architecture (ontology/manufacture.ttl) -- this is ordinary source at its
ordinary import path, additive only, and is not wired into any existing
runtime code path (no planner, no level4_crown, no gymact bridge imports it).

Object-property fields hold an identity-reference string (the referenced
object's own identity), never a resolved object -- this is a thin semantic
projection, not an ORM. Non-functional properties render as a tuple of
reference strings; functional properties render as an optional single
reference string. The ontology asserts no required cardinality anywhere, so
every field defaults to empty/None rather than being required.

GENERATED by ggen. DO NOT EDIT BY HAND -- edit the source ontology/*.ttl file
and re-run `ggen sync run` from the repo root to regenerate.
"""
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum



@dataclass(frozen=True)
class CandidateSet:
    """The common constitutional meeting point for every candidate producer."""
    contains_candidate: tuple[str, ...] = ()  #  (ref: PlanCandidate)
    records_disagreement: tuple[str, ...] = ()  #  (ref: Disagreement)


@dataclass(frozen=True)
class Critique:
    """Critique"""
    critiques_candidate: tuple[str, ...] = ()  #  (ref: PlanCandidate)


@dataclass(frozen=True)
class Disagreement:
    """Disagreement"""


@dataclass(frozen=True)
class DiscriminatingProbe:
    """An experiment or observation selected to distinguish unresolved planner/model hypotheses."""
    designed_from_disagreement: tuple[str, ...] = ()  #  (ref: Disagreement)


@dataclass(frozen=True)
class GovernedCandidate:
    """A plan candidate that obtained standing through the common candidate-set critique and validation path."""
    admitted_from_candidate_set: tuple[str, ...] = ()  #  (ref: CandidateSet)
    governs_candidate: tuple[str, ...] = ()  #  (ref: PlanCandidate)


@dataclass(frozen=True)
class PlanCandidate:
    """A candidate future proposed by any producer. It is not commitment authority."""
    candidate_for_trial: tuple[str, ...] = ()  #  (ref: Trial)


@dataclass(frozen=True)
class Planner:
    """Planner"""


@dataclass(frozen=True)
class PlannerAttempt:
    """PlannerAttempt"""
    attempted_by: tuple[str, ...] = ()  #  (ref: Planner)
    produced_candidate: tuple[str, ...] = ()  #  (ref: PlanCandidate)
    solves_problem: tuple[str, ...] = ()  #  (ref: PlanningProblem)


@dataclass(frozen=True)
class PlanningProblem:
    """PlanningProblem"""


@dataclass(frozen=True)
class Validation:
    """Validation"""
    validates_candidate: tuple[str, ...] = ()  #  (ref: PlanCandidate)


__all__ = [
    "CandidateSet",
    "Critique",
    "Disagreement",
    "DiscriminatingProbe",
    "GovernedCandidate",
    "PlanCandidate",
    "Planner",
    "PlannerAttempt",
    "PlanningProblem",
    "Validation",
]
