"""AutoFDE Lab semantic constitution — direct Python projection.

Manufactured by `ggen sync run` from an ontology/*.ttl file in the merged
working-backwards Lab constitution (PR #37). Manufacture is provenance, not
architecture (ontology/manufacture.ttl) -- this is ordinary source at its
ordinary import path, additive only, and is not wired into any existing
runtime code path (no planner, no level4_crown, no gymact bridge imports it).

Object-property fields hold an identity-reference string (the referenced
object's own identity), never a resolved object -- this is a thin semantic
projection, not an ORM. Non-functional properties render as a tuple of
reference strings; functional properties render as an optional single
reference string. The ontology asserts no required cardinality anywhere, so
every field defaults to empty/None rather than being required.

GENERATED by ggen. DO NOT EDIT BY HAND -- edit the source ontology/*.ttl file
and re-run `ggen sync run` from the repo root to regenerate.
"""
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum



class StandingValue(str, Enum):
    """Status-vocabulary named individuals from this ontology file."""

    DO = "DO"
    PURE = "PURE"
    READ = "READ"
    VERIFY = "VERIFY"



@dataclass(frozen=True)
class Activity:
    """A labelled process step with an explicit consequence class. DSPy reasons and constructs candidate activities; it never itself performs a DO-consequence activity's real effect -- that routes through GymAct/BRCE, unchanged by this vocabulary."""
    estimated_cost: str | None = None  #  (ref: http://www.w3.org/2001/XMLSchema#double)
    expected_information_gain: str | None = None  #  (ref: http://www.w3.org/2001/XMLSchema#double)
    has_consequence: str | None = None  #  (ref: ConsequenceClass)
    required_capability_class: str | None = None  # A named capability class an executor must resolve to a real, gated capability before this Activity may run -- never resolved by this vocabulary itself. (ref: http://www.w3.org/2001/XMLSchema#string)


@dataclass(frozen=True)
class ChoiceGraph:
    """ChoiceGraph"""


@dataclass(frozen=True)
class Guard:
    """A named, evaluable predicate on a choice-graph transition. Guard evaluation is deterministic and external to this vocabulary -- the ontology names the predicate, it does not define its truth."""
    guard_predicate: str | None = None  # A named predicate identifier (e.g. 'causal_closure') an external, deterministic evaluator resolves against the current epistemic state. (ref: http://www.w3.org/2001/XMLSchema#string)
    guards_edge: str | None = None  #  (ref: ProcessNode)


@dataclass(frozen=True)
class OrderEdge:
    """One direct/generating precedence edge. The mathematical strict partial-order relation is its acyclic reachability closure."""
    after_node: str | None = None  #  (ref: ProcessNode)
    before_node: str | None = None  #  (ref: ProcessNode)


@dataclass(frozen=True)
class POWLCommitment:
    """An exact partial-order commitment derived only from a governed candidate. It does not itself grant actuation authority."""
    commits_to: str | None = None  # The range is deliberately GovernedCandidate, preventing raw plan candidates from being the semantic commitment target. (ref: GovernedCandidate)
    committed_process: str | None = None  #  (ref: POWLProcess)


@dataclass(frozen=True)
class POWLProcess:
    """POWLProcess"""
    has_root_node: str | None = None  #  (ref: ProcessNode)
    preserves_node: tuple[str, ...] = ()  #  (ref: ProcessNode)
    repair_of: tuple[str, ...] = ()  #  (ref: POWLProcess)


@dataclass(frozen=True)
class PartialOrderComposite:
    """PartialOrderComposite"""
    has_order_edge: tuple[str, ...] = ()  #  (ref: OrderEdge)


@dataclass(frozen=True)
class ProcessNode:
    """ProcessNode"""
    affected_by_perturbation: tuple[str, ...] = ()  #  (ref: Perturbation)
    has_child_node: tuple[str, ...] = ()  #  (ref: ProcessNode)
    precedes: tuple[str, ...] = ()  # Semantic strict precedence derived from reachability, not necessarily materialized on the wire. (ref: ProcessNode)


@dataclass(frozen=True)
class SilentTransition:
    """SilentTransition"""


@dataclass(frozen=True)
class TransitionNode:
    """TransitionNode"""


__all__ = [
    "StandingValue",
    "Activity",
    "ChoiceGraph",
    "Guard",
    "OrderEdge",
    "POWLCommitment",
    "POWLProcess",
    "PartialOrderComposite",
    "ProcessNode",
    "SilentTransition",
    "TransitionNode",
]
