"""AutoFDE Lab semantic constitution — direct Python projection.

Manufactured by `ggen sync run` from an ontology/*.ttl file in the merged
working-backwards Lab constitution (PR #37). Manufacture is provenance, not
architecture (ontology/manufacture.ttl) -- this is ordinary source at its
ordinary import path, additive only, and is not wired into any existing
runtime code path (no planner, no level4_crown, no gymact bridge imports it).

Object-property fields hold an identity-reference string (the referenced
object's own identity), never a resolved object -- this is a thin semantic
projection, not an ORM. Non-functional properties render as a tuple of
reference strings; functional properties render as an optional single
reference string. The ontology asserts no required cardinality anywhere, so
every field defaults to empty/None rather than being required.

GENERATED by ggen. DO NOT EDIT BY HAND -- edit the source ontology/*.ttl file
and re-run `ggen sync run` from the repo root to regenerate.
"""
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum



class StandingValue(str, Enum):
    """Status-vocabulary named individuals from this ontology file."""

    ALIVE = "ALIVE"
    BLOCKED = "BLOCKED"
    BUILD_BROKEN = "BUILD_BROKEN"
    PARTIAL_ALIVE = "PARTIAL_ALIVE"
    UNKNOWN = "UNKNOWN"
    UNSUPPORTED = "UNSUPPORTED"



@dataclass(frozen=True)
class Refusal:
    """Refusal"""
    refusal_code: tuple[str, ...] = ()  #  (ref: http://www.w3.org/2001/XMLSchema#string)
    refusal_reason: tuple[str, ...] = ()  #  (ref: http://www.w3.org/2001/XMLSchema#string)


@dataclass(frozen=True)
class StandingAssertion:
    """A derived, scoped statement about a subject's standing."""
    derived_from_witness: tuple[str, ...] = ()  #  (ref: EvidenceWitness)
    standing_subject: str | None = None  # 
    standing_value: str | None = None  #  (ref: StandingValue)


__all__ = [
    "StandingValue",
    "Refusal",
    "StandingAssertion",
]
