"""AutoFDE Lab semantic constitution — direct Python projection.

Manufactured by `ggen sync run` from an ontology/*.ttl file in the merged
working-backwards Lab constitution (PR #37). Manufacture is provenance, not
architecture (ontology/manufacture.ttl) -- this is ordinary source at its
ordinary import path, additive only, and is not wired into any existing
runtime code path (no planner, no level4_crown, no gymact bridge imports it).

Object-property fields hold an identity-reference string (the referenced
object's own identity), never a resolved object -- this is a thin semantic
projection, not an ORM. Non-functional properties render as a tuple of
reference strings; functional properties render as an optional single
reference string. The ontology asserts no required cardinality anywhere, so
every field defaults to empty/None rather than being required.

GENERATED by ggen. DO NOT EDIT BY HAND -- edit the source ontology/*.ttl file
and re-run `ggen sync run` from the repo root to regenerate.
"""
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum



@dataclass(frozen=True)
class AdmittedObservation:
    """An observation accepted for a bounded decision or experiment after its required admission checks."""
    derived_from_observation: tuple[str, ...] = ()  #  (ref: Observation)


@dataclass(frozen=True)
class Environment:
    """Environment"""


@dataclass(frozen=True)
class Observation:
    """Raw observed information. Observation is not admission."""
    about_state: tuple[str, ...] = ()  #  (ref: WorldState)
    observed_from: tuple[str, ...] = ()  #  (ref: World)


@dataclass(frozen=True)
class ObservationAdmission:
    """ObservationAdmission"""
    admits_observation: tuple[str, ...] = ()  #  (ref: AdmittedObservation)


@dataclass(frozen=True)
class World:
    """World"""


@dataclass(frozen=True)
class WorldState:
    """WorldState"""


__all__ = [
    "AdmittedObservation",
    "Environment",
    "Observation",
    "ObservationAdmission",
    "World",
    "WorldState",
]
