(define (problem ecosystem-full-crown)
  (:domain autofde-meta-planning)
  (:objects
    p01 p02 p03 p04 p05 p06 p07 p08 p09 p10 p11 p12 p13 p14 p15 p16 p17 p18 p19 p20 p21 p22 p23 p24 p25 p26 p27 p28 p29 p30 p31 p32 p33 p34 p35 p36 p37 p38 p39 p40 p41 p42 p43 p44 p45 p46 p47 p48 p49 p50 - planner
    accomplish falsify - role
    enterprise-world - world
    ecosystem-subject - subject)
  (:init
    (observation-admitted ecosystem-subject)
    (world-allowed enterprise-world)
    (constructor-role accomplish)
    (falsifier-role falsify)
    (planner-available p01)
    (planner-available p02)
    (planner-available p03)
    (planner-available p04)
    (planner-available p05)
    (planner-available p06)
    (planner-available p07)
    (planner-available p08)
    (planner-available p09)
    (planner-available p10)
    (planner-available p11)
    (planner-available p12)
    (planner-available p13)
    (planner-available p14)
    (planner-available p15)
    (planner-available p16)
    (planner-available p17)
    (planner-available p18)
    (planner-available p19)
    (planner-available p20)
    (planner-available p21)
    (planner-available p22)
    (planner-available p23)
    (planner-available p24)
    (planner-available p25)
    (planner-available p26)
    (planner-available p27)
    (planner-available p28)
    (planner-available p29)
    (planner-available p30)
    (planner-available p31)
    (planner-available p32)
    (planner-available p33)
    (planner-available p34)
    (planner-available p35)
    (planner-available p36)
    (planner-available p37)
    (planner-available p38)
    (planner-available p39)
    (planner-available p40)
    (planner-available p41)
    (planner-available p42)
    (planner-available p43)
    (planner-available p44)
    (planner-available p45)
    (planner-available p46)
    (planner-available p47)
    (planner-available p48)
    (planner-available p49)
    (planner-available p50)
    (compatible p01 accomplish)
    (compatible p01 falsify)
    (compatible p02 accomplish)
    (compatible p02 falsify)
    (compatible p03 accomplish)
    (compatible p03 falsify)
    (compatible p04 accomplish)
    (compatible p04 falsify)
    (compatible p05 accomplish)
    (compatible p05 falsify)
    (compatible p06 accomplish)
    (compatible p06 falsify)
    (compatible p07 accomplish)
    (compatible p07 falsify)
    (compatible p08 accomplish)
    (compatible p08 falsify)
    (compatible p09 accomplish)
    (compatible p09 falsify)
    (compatible p10 accomplish)
    (compatible p10 falsify)
    (compatible p11 accomplish)
    (compatible p11 falsify)
    (compatible p12 accomplish)
    (compatible p12 falsify)
    (compatible p13 accomplish)
    (compatible p13 falsify)
    (compatible p14 accomplish)
    (compatible p14 falsify)
    (compatible p15 accomplish)
    (compatible p15 falsify)
    (compatible p16 accomplish)
    (compatible p16 falsify)
    (compatible p17 accomplish)
    (compatible p17 falsify)
    (compatible p18 accomplish)
    (compatible p18 falsify)
    (compatible p19 accomplish)
    (compatible p19 falsify)
    (compatible p20 accomplish)
    (compatible p20 falsify)
    (compatible p21 accomplish)
    (compatible p21 falsify)
    (compatible p22 accomplish)
    (compatible p22 falsify)
    (compatible p23 accomplish)
    (compatible p23 falsify)
    (compatible p24 accomplish)
    (compatible p24 falsify)
    (compatible p25 accomplish)
    (compatible p25 falsify)
    (compatible p26 accomplish)
    (compatible p26 falsify)
    (compatible p27 accomplish)
    (compatible p27 falsify)
    (compatible p28 accomplish)
    (compatible p28 falsify)
    (compatible p29 accomplish)
    (compatible p29 falsify)
    (compatible p30 accomplish)
    (compatible p30 falsify)
    (compatible p31 accomplish)
    (compatible p31 falsify)
    (compatible p32 accomplish)
    (compatible p32 falsify)
    (compatible p33 accomplish)
    (compatible p33 falsify)
    (compatible p34 accomplish)
    (compatible p34 falsify)
    (compatible p35 accomplish)
    (compatible p35 falsify)
    (compatible p36 accomplish)
    (compatible p36 falsify)
    (compatible p37 accomplish)
    (compatible p37 falsify)
    (compatible p38 accomplish)
    (compatible p38 falsify)
    (compatible p39 accomplish)
    (compatible p39 falsify)
    (compatible p40 accomplish)
    (compatible p40 falsify)
    (compatible p41 accomplish)
    (compatible p41 falsify)
    (compatible p42 accomplish)
    (compatible p42 falsify)
    (compatible p43 accomplish)
    (compatible p43 falsify)
    (compatible p44 accomplish)
    (compatible p44 falsify)
    (compatible p45 accomplish)
    (compatible p45 falsify)
    (compatible p46 accomplish)
    (compatible p46 falsify)
    (compatible p47 accomplish)
    (compatible p47 falsify)
    (compatible p48 accomplish)
    (compatible p48 falsify)
    (compatible p49 accomplish)
    (compatible p49 falsify)
    (compatible p50 accomplish)
    (compatible p50 falsify))

  ;; p01..p50 are symbolic league slots, not concrete compatibility claims.
  ;; Replace fixture compatibility with the admitted live registry matrix.
  (:goal (and
    (handoff-ready ecosystem-subject enterprise-world)
    (falsification-complete ecosystem-subject enterprise-world)
    (verifier-ready ecosystem-subject enterprise-world)
    (recovery-ready ecosystem-subject enterprise-world)))
)
