(define (problem world-cyber-role-conditioned-self-play)
  (:domain autofde-meta-planning)
  (:objects
    p01 p02 p03 p04 p05 p06 p07 p08 p09 p10 p11 p12 p13 p14 p15 p16 p17 p18 p19 p20 p21 p22 p23 p24 p25 p26 p27 p28 p29 p30 p31 p32 p33 p34 p35 p36 p37 p38 p39 p40 p41 p42 p43 p44 p45 p46 p47 p48 p49 p50 - planner
    blue red - role
    world-cyber - world
    cyber-subject - subject)
  (:init
    (observation-admitted cyber-subject)
    (world-allowed world-cyber)
    (constructor-role blue)
    (falsifier-role red)
    (planner-available p01)
    (planner-available p02)
    (planner-available p03)
    (planner-available p04)
    (planner-available p05)
    (planner-available p06)
    (planner-available p07)
    (planner-available p08)
    (planner-available p09)
    (planner-available p10)
    (planner-available p11)
    (planner-available p12)
    (planner-available p13)
    (planner-available p14)
    (planner-available p15)
    (planner-available p16)
    (planner-available p17)
    (planner-available p18)
    (planner-available p19)
    (planner-available p20)
    (planner-available p21)
    (planner-available p22)
    (planner-available p23)
    (planner-available p24)
    (planner-available p25)
    (planner-available p26)
    (planner-available p27)
    (planner-available p28)
    (planner-available p29)
    (planner-available p30)
    (planner-available p31)
    (planner-available p32)
    (planner-available p33)
    (planner-available p34)
    (planner-available p35)
    (planner-available p36)
    (planner-available p37)
    (planner-available p38)
    (planner-available p39)
    (planner-available p40)
    (planner-available p41)
    (planner-available p42)
    (planner-available p43)
    (planner-available p44)
    (planner-available p45)
    (planner-available p46)
    (planner-available p47)
    (planner-available p48)
    (planner-available p49)
    (planner-available p50)
    (compatible p01 blue)
    (compatible p01 red)
    (compatible p02 blue)
    (compatible p02 red)
    (compatible p03 blue)
    (compatible p03 red)
    (compatible p04 blue)
    (compatible p04 red)
    (compatible p05 blue)
    (compatible p05 red)
    (compatible p06 blue)
    (compatible p06 red)
    (compatible p07 blue)
    (compatible p07 red)
    (compatible p08 blue)
    (compatible p08 red)
    (compatible p09 blue)
    (compatible p09 red)
    (compatible p10 blue)
    (compatible p10 red)
    (compatible p11 blue)
    (compatible p11 red)
    (compatible p12 blue)
    (compatible p12 red)
    (compatible p13 blue)
    (compatible p13 red)
    (compatible p14 blue)
    (compatible p14 red)
    (compatible p15 blue)
    (compatible p15 red)
    (compatible p16 blue)
    (compatible p16 red)
    (compatible p17 blue)
    (compatible p17 red)
    (compatible p18 blue)
    (compatible p18 red)
    (compatible p19 blue)
    (compatible p19 red)
    (compatible p20 blue)
    (compatible p20 red)
    (compatible p21 blue)
    (compatible p21 red)
    (compatible p22 blue)
    (compatible p22 red)
    (compatible p23 blue)
    (compatible p23 red)
    (compatible p24 blue)
    (compatible p24 red)
    (compatible p25 blue)
    (compatible p25 red)
    (compatible p26 blue)
    (compatible p26 red)
    (compatible p27 blue)
    (compatible p27 red)
    (compatible p28 blue)
    (compatible p28 red)
    (compatible p29 blue)
    (compatible p29 red)
    (compatible p30 blue)
    (compatible p30 red)
    (compatible p31 blue)
    (compatible p31 red)
    (compatible p32 blue)
    (compatible p32 red)
    (compatible p33 blue)
    (compatible p33 red)
    (compatible p34 blue)
    (compatible p34 red)
    (compatible p35 blue)
    (compatible p35 red)
    (compatible p36 blue)
    (compatible p36 red)
    (compatible p37 blue)
    (compatible p37 red)
    (compatible p38 blue)
    (compatible p38 red)
    (compatible p39 blue)
    (compatible p39 red)
    (compatible p40 blue)
    (compatible p40 red)
    (compatible p41 blue)
    (compatible p41 red)
    (compatible p42 blue)
    (compatible p42 red)
    (compatible p43 blue)
    (compatible p43 red)
    (compatible p44 blue)
    (compatible p44 red)
    (compatible p45 blue)
    (compatible p45 red)
    (compatible p46 blue)
    (compatible p46 red)
    (compatible p47 blue)
    (compatible p47 red)
    (compatible p48 blue)
    (compatible p48 red)
    (compatible p49 blue)
    (compatible p49 red)
    (compatible p50 blue)
    (compatible p50 red))

  ;; p01..p50 are symbolic league slots, not concrete compatibility claims.
  ;; Replace fixture compatibility with the admitted live registry matrix.
  (:goal (and
    (handoff-ready cyber-subject world-cyber)
    (falsification-complete cyber-subject world-cyber)))
)
